import React, { createContext, useContext, useState, useEffect } from 'react';

const LANG_KEY = 'doctracking_lang';

const T = {
  en: {
    appName:    'Document Tracking System',
    orgName:    'General Administration of Sunni Endowments',
    signIn:     'Sign In',
    signOut:    'Sign Out',
    signingIn:  'Signing in…',
    username:   'Username',
    password:   'Password',
    usernamePH: 'Username or user@domain.com',
    welcome:    'Welcome',
    dept:       'Department',
    adminPanel: 'Admin Panel',
    loading:    'Loading…',
    na:         'N/A',
    departments:'Departments',
    newRecord:  'New Record',
    submit:     'Submit',
    reset:      'Reset',
    required:   'Required',
    save:       'Save',
    cancel:     'Cancel',
    edit:       'Edit',
    del:        'Delete',
    add:        'Add',
    confirmDel: 'Are you sure? This cannot be undone.',
    selectDept: 'Select a department from the sidebar to begin.',
    submitted:  'Submitted successfully.',
    deptFields: 'Departments & Fields',
    roleMaps:   'Role Mappings',
    config:     'Config',
    addDept:    '+ Add Department',
    deptLabel:  'Department label',
    adGroup:    'AD Group CN',
    fields:     'fields',
    addField:   '+ Add Field',
    fieldKey:   'Field key',
    fieldLabel: 'Display label',
    fieldType:  'Type',
    fieldReq:   'Required',
    optionsPH:  'Option1, Option2, Option3',
    actions:    'Actions',
    optPH:      'Options / Placeholder',
    exportJSON: '⬇ Export JSON',
    previewCfg: 'Preview config',
    importCfg:  '⬆ Import & Apply',
    importPH:   '{"departments": [...], "roleGroupMap": {...}}',
    importNote: 'Paste JSON to import (replaces everything):',
    cfgNote:    'All settings are stored in server/config/departments.json.',
    ldapNote:   'AD group name (CN, lowercase) mapped to a role. Changes apply on next login.',
    roleMap:    'LDAP Group → Role Mappings',
    newGroup:   'new_group_cn',

    // Navigation
    dashboard:  'Dashboard',
    tasks:      'Tasks',
    myTasks:    'My Tasks',
    allTasks:   'All Tasks',
    users:      'Users',
    settings:   'Settings',
    deptForms:  'Department Forms',

    // Task workflow
    createTask:     'Create Task',
    taskTitle:      'Task Title',
    taskType:       'Type',
    taskPriority:   'Priority',
    taskStatus:     'Status',
    taskSerial:     'Serial',
    taskCreated:    'Created',
    taskAssigned:   'Assigned To',
    taskSource:     'Source / Sender',
    taskDelivery:   'Delivery Method',
    taskExpected:   'Expected Completion',
    taskCompleted:  'Completed On',
    taskNote:       'Notes',
    forwardTask:    'Forward to Department',
    returnToCS:     'Return to CS',
    closeTask:      'Close Task',
    addComment:     'Add Comment',
    taskHistory:    'Activity History',
    selectDeptFwd:  'Select destination department',
    confirmClose:   'Are you sure you want to close this task?',
    confirmReturn:  'Return this task to Customer Service?',
    taskClosed:     'Task closed successfully.',
    taskForwarded:  'Task forwarded.',
    taskReturned:   'Task returned to CS.',
    commentAdded:   'Comment added.',

    types:     { incoming: 'Incoming', outgoing: 'Outgoing' },
    priorities:{ low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent' },
    statuses:  { new: 'New', assigned: 'Assigned', in_progress: 'In Progress', returned: 'Returned', closed: 'Closed' },
    eventTypes:{
      created:   'Task created',
      forwarded: 'Forwarded to',
      returned:  'Returned to CS',
      commented: 'Comment',
      closed:    'Closed',
    },

    // Users
    fullName:     'Full Name',
    email:        'Email',
    role:         'Role',
    deptAssign:   'Department',
    active:       'Active',
    inactive:     'Inactive',
    addUser:      '+ Add User',
    editUser:     'Edit User',
    newPassword:  'New Password (leave blank to keep current)',
    userCreated:  'User created.',
    userUpdated:  'User updated.',
    userDeleted:  'User deleted.',

    // Dashboard
    totalTasks:    'Total Tasks',
    openTasks:     'Open',
    closedTasks:   'Closed',
    returnedTasks: 'Returned',
    totalUsers:    'Total Users',
    byDept:        'Tasks by Department',
    recentTasks:   'Recent Tasks',
    noTasks:       'No tasks yet.',
    noUsers:       'No users yet.',

    overdue:           'Overdue',
    overdueTasks:      'Overdue Tasks',
    notifications:     'Notifications',
    markAllRead:       'Mark all read',
    noNotifications:   'No notifications yet.',
    search:            'Search…',
    roles: {
      SUPER_ADMIN:      'Super Admin',
      ADMIN:            'Admin',
      CUSTOMER_SERVICE: 'Customer Service',
      MANAGER:          'Manager',
      STAFF:            'Staff',
      READONLY:         'Read Only',
    },
    groupLabels: {
      customer_service:       'Customer Service',
      accounts_dept:          'Accounts',
      banks_dept:             'Banks & Social',
      asset_development_dept: 'Asset Development',
    },
  },

  ar: {
    appName:    'نظام تتبع الوثائق',
    orgName:    'الإدارة العامة للأوقاف السنية',
    signIn:     'تسجيل الدخول',
    signOut:    'خروج',
    signingIn:  'جاري الدخول…',
    username:   'اسم المستخدم',
    password:   'كلمة المرور',
    usernamePH: 'اسم المستخدم أو البريد الإلكتروني',
    welcome:    'مرحباً',
    dept:       'القسم',
    adminPanel: 'الإعدادات',
    loading:    'جاري التحميل…',
    na:         'غير محدد',
    departments:'الأقسام',
    newRecord:  'سجل جديد',
    submit:     'إرسال',
    reset:      'إعادة تعيين',
    required:   'مطلوب',
    save:       'حفظ',
    cancel:     'إلغاء',
    edit:       'تعديل',
    del:        'حذف',
    add:        'إضافة',
    confirmDel: 'هل أنت متأكد؟ لا يمكن التراجع.',
    selectDept: 'اختر قسماً من القائمة الجانبية للبدء.',
    submitted:  'تم الإرسال بنجاح.',
    deptFields: 'الأقسام والحقول',
    roleMaps:   'تعيين الصلاحيات',
    config:     'الإعدادات',
    addDept:    '+ إضافة قسم',
    deptLabel:  'اسم القسم',
    adGroup:    'مجموعة AD',
    fields:     'حقل',
    addField:   '+ إضافة حقل',
    fieldKey:   'مفتاح الحقل',
    fieldLabel: 'التسمية',
    fieldType:  'النوع',
    fieldReq:   'مطلوب',
    optionsPH:  'خيار1، خيار2، خيار3',
    actions:    'الإجراءات',
    optPH:      'الخيارات / النص التوضيحي',
    exportJSON: '⬇ تصدير JSON',
    previewCfg: 'معاينة الإعدادات',
    importCfg:  '⬆ استيراد وتطبيق',
    importPH:   '{"departments": [...], "roleGroupMap": {...}}',
    importNote: 'الصق JSON للاستيراد (يستبدل كل شيء):',
    cfgNote:    'جميع الإعدادات محفوظة في server/config/departments.json.',
    ldapNote:   'اسم مجموعة AD مرتبط بدور. التغييرات تُطبَّق عند تسجيل الدخول التالي.',
    roleMap:    'مجموعات LDAP ← الأدوار',
    newGroup:   'اسم_المجموعة',

    // Navigation
    dashboard:  'لوحة المتابعة',
    tasks:      'المهام',
    myTasks:    'مهامي',
    allTasks:   'جميع المهام',
    users:      'المستخدمون',
    settings:   'إعدادات النظام',
    deptForms:  'نماذج الأقسام',

    // Task workflow
    createTask:     'إنشاء مهمة',
    taskTitle:      'عنوان المهمة',
    taskType:       'النوع',
    taskPriority:   'الأولوية',
    taskStatus:     'الحالة',
    taskSerial:     'الرقم التسلسلي',
    taskCreated:    'تاريخ الإنشاء',
    taskAssigned:   'محال إلى',
    taskSource:     'الجهة المرسلة',
    taskDelivery:   'طريقة الاستلام',
    taskExpected:   'تاريخ الإنجاز المتوقع',
    taskCompleted:  'تاريخ الإنجاز الفعلي',
    taskNote:       'ملاحظات',
    forwardTask:    'إحالة إلى قسم',
    returnToCS:     'إرجاع لخدمة العملاء',
    closeTask:      'إغلاق المهمة',
    addComment:     'إضافة تعليق',
    taskHistory:    'سجل النشاط',
    selectDeptFwd:  'اختر القسم المحال إليه',
    confirmClose:   'هل تريد إغلاق هذه المهمة؟',
    confirmReturn:  'هل تريد إرجاع المهمة إلى خدمة العملاء؟',
    taskClosed:     'تم إغلاق المهمة.',
    taskForwarded:  'تم إحالة المهمة.',
    taskReturned:   'تم إرجاع المهمة لخدمة العملاء.',
    commentAdded:   'تمت إضافة التعليق.',

    types:     { incoming: 'وارد', outgoing: 'صادر' },
    priorities:{ low: 'منخفضة', normal: 'عادية', high: 'عالية', urgent: 'عاجلة' },
    statuses:  { new: 'جديدة', assigned: 'محالة', in_progress: 'قيد التنفيذ', returned: 'مُرجَعة', closed: 'مغلقة' },
    eventTypes:{
      created:   'تم إنشاء المهمة',
      forwarded: 'أُحيلت إلى',
      returned:  'أُرجعت لخدمة العملاء',
      commented: 'تعليق',
      closed:    'تم الإغلاق',
    },

    // Users
    fullName:     'الاسم الكامل',
    email:        'البريد الإلكتروني',
    role:         'الدور',
    deptAssign:   'القسم',
    active:       'نشط',
    inactive:     'غير نشط',
    addUser:      '+ إضافة مستخدم',
    editUser:     'تعديل المستخدم',
    newPassword:  'كلمة مرور جديدة (اتركها فارغة للإبقاء على الحالية)',
    userCreated:  'تم إنشاء المستخدم.',
    userUpdated:  'تم تحديث المستخدم.',
    userDeleted:  'تم حذف المستخدم.',

    // Dashboard
    totalTasks:    'إجمالي المهام',
    openTasks:     'مفتوحة',
    closedTasks:   'مغلقة',
    returnedTasks: 'مُرجَعة',
    totalUsers:    'المستخدمون',
    byDept:        'المهام حسب القسم',
    recentTasks:   'أحدث المهام',
    noTasks:       'لا توجد مهام بعد.',
    noUsers:       'لا يوجد مستخدمون بعد.',

    overdue:           'متأخرة',
    overdueTasks:      'المهام المتأخرة',
    notifications:     'الإشعارات',
    markAllRead:       'تعليم الكل كمقروء',
    noNotifications:   'لا توجد إشعارات بعد.',
    search:            'بحث…',
    roles: {
      SUPER_ADMIN:      'مدير النظام',
      ADMIN:            'مشرف',
      CUSTOMER_SERVICE: 'خدمة العملاء',
      MANAGER:          'مدير',
      STAFF:            'موظف',
      READONLY:         'قراءة فقط',
    },
    groupLabels: {
      customer_service:       'خدمة العملاء',
      accounts_dept:          'قسم الحسابات',
      banks_dept:             'قسم المصارف',
      asset_development_dept: 'تنمية الأصول الوقفية',
    },
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LANG_KEY) || 'ar');

  useEffect(() => {
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir  = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const toggle = () => setLang(l => (l === 'ar' ? 'en' : 'ar'));
  const isRTL  = lang === 'ar';
  const t      = T[lang];

  return (
    <LangContext.Provider value={{ lang, t, toggle, isRTL }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be inside <LangProvider>');
  return ctx;
}
