import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LANG_KEY = 'doctracking_lang';

const T = {
  en: {
    appName:    'Document Tracking System',
    orgName:    'General Directorate of Sunni Affairs',
    loginSubtitle: 'Enter your corporate credentials',
    loginFeatures: [
      'Track official inbound & outbound correspondence',
      'Manage public inquiries and service requests',
      'Follow up on contracts, cheques & social research',
      'Full admin panel with LDAP role management',
    ],
    signIn:     'Sign In',
    signOut:    'Sign Out',
    signingIn:  'Signing in…',
    username:   'Username',
    password:   'Password',
    usernamePH: 'Username or user@domain.com',
    welcome:    'Welcome',
    dept:       'Department',
    adminPanel: 'Admin Panel',
    loading:    'Loading…',
    na:         'N/A',
    departments:'Departments',
    newRecord:  'New Record',
    submit:     'Submit',
    reset:      'Reset',
    required:   'Required',
    save:       'Save',
    cancel:     'Cancel',
    edit:       'Edit',
    del:        'Delete',
    add:        'Add',
    confirmDel: 'Are you sure? This cannot be undone.',
    selectDept: 'Select a department from the sidebar to begin.',
    submitted:  'Submitted successfully.',
    deptFields:       'Departments',
    roleMaps:         'AD Auto-Roles',
    config:           'Backup',
    addDept:          'Add Department',
    deptLabel:        'Department Name',
    adGroup:          'AD Group (optional)',
    adGroupHint:      'The Active Directory group CN linked to this department (used for automatic task routing).',
    fields:           'fields',
    addField:         '+ Add Field',
    fieldKey:         'Field key',
    fieldLabel:       'Display label',
    fieldType:        'Type',
    fieldReq:         'Required',
    optionsPH:        'Option1, Option2, Option3',
    actions:          'Actions',
    optPH:            'Options / Placeholder',
    exportJSON:       'Download Backup',
    previewCfg:       'Preview',
    importCfg:        'Import & Apply',
    importPH:         '{"departments": [...], "roleGroupMap": {...}}',
    importNote:       'Paste a backup JSON to restore (replaces all departments and role mappings):',
    cfgNote:          'Download a backup of all department and role settings, or restore from a previous backup.',
    ldapNote:         'When an AD user logs in without a manually assigned role, their group membership is used to auto-assign a role. Add the group CN and choose a role.',
    adAutoRolesNote:  'These rules run automatically on login. For manual role assignment per person, use the Users page instead.',
    roleMap:          'AD Group → Auto Role',
    newGroup:         'group_cn_name',
    deptNote:         'Departments appear immediately in all dropdowns (users, task creation) after saving.',
    usersInDept:      'users',
    advancedOptions:  'Advanced',
    customFields:     'Custom Fields',
    customFieldsNote: 'Extra fields shown when creating a task for this department.',
    noDepts:          'No departments yet. Add one to get started.',

    // Bulk actions
    selectAll:        'Select all',
    selected:         'selected',
    bulkForward:      'Forward All',
    bulkClose:        'Close All',
    clearSelection:   'Clear',
    bulkDone:         'Done — {n} tasks updated.',
    selectDeptBulk:   'Forward {n} tasks to:',

    // Task templates
    templates:        'Templates',
    templateName:     'Template Name',
    useTemplate:      'Use Template',
    noTemplate:       'No Template',
    addTemplate:      'Add Template',
    editTemplate:     'Edit Template',
    templateSaved:    'Template saved.',
    templateDeleted:  'Template deleted.',
    noTemplates:      'No templates yet.',
    expectedDays:     'Expected Days',
    templatesNote:    'Pre-fill common task fields. Available to all staff when creating tasks.',

    // Sessions
    activeSessions:   'Active Sessions',
    sessionsNote:     'All currently logged-in users. Force logout terminates their session immediately.',
    forceLogout:      'Force Logout',
    sessionTerminated:'Session terminated.',
    noSessions:       'No active sessions.',
    loggedInAt:       'Logged in',
    expiresAt:        'Expires',
    yourSession:      'You',

    // Audit log
    auditLog:         'Audit Log',
    auditActor:       'User',
    auditAction:      'Action',
    auditTarget:      'Target',
    auditTime:        'Time',
    auditFilter:      'Filter by user…',
    noAuditLogs:      'No log entries.',
    auditActions: {
      USER_LOGIN:          'Logged in',
      USER_LOGOUT:         'Logged out',
      TASK_CREATED:        'Task created',
      TASK_FORWARDED:      'Task forwarded',
      TASK_CLOSED:         'Task closed',
      USER_CREATED:        'User created',
      USER_UPDATED:        'User updated',
      USER_DELETED:        'User deleted',
      LDAP_ROLE_ASSIGNED:  'Role assigned',
      SESSION_TERMINATED:  'Session terminated',
    },

    // Dashboard dept filter
    allDepartments:   'All Departments',
    viewingDept:      'Viewing:',
    deptStats:        'Department Stats',

    // Navigation
    dashboard:  'Dashboard',
    tasks:      'Tasks',
    comingSoon:      'Coming soon.',
    exportCSV:       'Export to CSV',
    showOriginal:    'Show original',
    showTranslation: 'Show translation',
    translate:       'Translate',
    translating:     'Translating…',
    translateFailed: 'Translation failed. Try again.',
    translateChat:   'Translate this chat',
    translateChatOn: 'Translating this chat',
    reassignTask:    'Reassign Task',
    reassignExplain: 'Move this task directly to another department without returning it to reception.',
    reassignNotePH:  'Reason for reassignment (optional)…',
    taskReassigned:  'Task reassigned successfully.',
    recentSenders:   'Recent Senders',
    deptQueue:       'Department Queue',
    deptQueueEmpty:  'No open tasks assigned to your department.',
    idleDays:        '{n}d idle',
    idleLabel:       'Idle',
    priorityUpdated: 'Priority updated.',
    escalatePriorityHint: 'Click to change priority',
    snooze2h:        'Snooze 2 hours',
    allSnoozed:      'All caught up — reminders snoozed.',
    taskCategory:    'Category',
    allCategories:   'All',
    catWork:         'Work',
    catPersonal:     'Personal',
    catFollowUp:     'Follow-up',
    allTasks:   'All Tasks',
    users:      'Users',
    settings:   'Settings',
    deptForms:  'Department Forms',

    // Task workflow
    createTask:     'Create Task',
    taskTitle:      'Task Title',
    taskType:       'Type',
    taskPriority:   'Priority',
    taskStatus:     'Status',
    taskSerial:     'Serial',
    taskCreated:    'Created',
    taskAssigned:   'Assigned To',
    taskSource:     'Source / Sender',
    taskDelivery:   'Delivery Method',
    taskExpected:   'Expected Completion',
    taskCompleted:  'Completed On',
    taskNote:       'Notes',
    forwardTask:    'Forward to Department',
    returnToCS:     'Return to CS',
    closeTask:      'Close Task',
    addComment:     'Add Comment',
    markReceived:   'Received',
    receivedAdded:  'Marked as received.',
    taskHistory:    'Activity History',
    selectDeptFwd:  'Select destination department',
    confirmClose:   'Are you sure you want to close this task?',
    confirmReturn:  'Return this task to Customer Service?',
    taskClosed:     'Task closed successfully.',
    taskForwarded:  'Task forwarded.',
    taskReturned:   'Task returned to CS.',
    commentAdded:   'Comment added.',

    types:     { incoming: 'Incoming', outgoing: 'Outgoing' },
    priorities:{ low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent' },
    statuses:  { new: 'New', assigned: 'Assigned', in_progress: 'In Progress', returned: 'Returned', closed: 'Closed' },
    eventTypes:{
      created:   'Task created',
      forwarded: 'Forwarded to',
      returned:  'Returned to CS',
      commented: 'Comment',
      closed:    'Closed',
    },

    // Create Task — CS wizard
    createTransaction:    'New Transaction',
    senderTypePerson:     'Person',
    senderTypeCompany:    'Company',
    senderTypeOther:      'Other',
    senderInfoLabel:      'Requester Information',
    enterSenderInfo:      'Enter the requester\'s information',
    senderLabel:          'Sender',
    companyOrEntityName:  'Company / Entity Name',
    phoneNumber:          'Phone Number',
    chooseDeptForTask:    'Choose the department for this transaction',
    chooseDeptPH:         'Choose department',
    nServices:            '{n} services',
    backToDepts:          'Departments',
    chooseServiceType:    'Choose the service type',
    noServicesForDept:    'No services added for this department',
    reviewerLabel:        'Requester:',
    changeBtn:             'Change',
    noFieldsForService:   'No fields for this service — the transaction will be created directly',
    nextBtn:              'Next',
    backBtn:              'Back',
    selectOptionPH:       '— Select —',
    searchServicePH:      'Search for a service or department...',
    formAutoSentToCS:     'This form will be sent automatically to Customer Service',
    formAutoSentToCSNote: 'This form will be sent automatically to Customer Service · All required fields are marked with *',
    changeType:           'Change Type',
    deliveryManual:       'Manual',
    deliveryMail:         'Mail',
    deliveryEmail:        'Email',
    deliveryFax:          'Fax',
    deliveryOther:        'Other',

    // Task detail
    returnedFromDeptBanner:   'Returned from department — awaiting Customer Service review',
    atCSNotSentBanner:        'At Customer Service — not yet sent',
    inProgressAtDept:         'In progress at {dept}',
    sentAwaitingReceipt:      'Sent to {dept} — awaiting receipt',
    cycleSuffix:              'cycle',
    confirmReceived:          'Receipt confirmed',
    acceptStart:              'Accept / Start',
    senderLabelField:         'Sender',
    nameField:                'Name',
    phoneField:               'Phone',
    yesValue:                 '✓ Yes',
    noValue:                  '✗ No',
    cyclesNote:               'forward/return cycles',
    cycleLabel:               'Cycle {n}',
    eventCreated:             'Task created',
    eventForwardedTo:         'Forwarded to',
    eventReturnedToCS:        'Returned to Customer Service',
    eventAcceptedStarted:     'Received / Started',
    eventCommented:           'Note',
    eventConsultation:        'Consultation →',
    eventClosed:              'Closed',
    consultationTag:          'Consultation',
    fromDeptLabel:            'from {dept}',
    selectDeptPH:             '— Select department —',
    notePHForDept:            'Note for the department…',
    returnExplain:            'The transaction will be returned to Customer Service for review. Add a note describing what was done.',
    returnNotePH:             'What was done? Is follow-up needed?',
    closeConfirmReturned:     'The returned transaction has been reviewed — close it permanently?',
    closeConfirmDefault:      'Are you sure you want to close this transaction permanently?',
    closingNotePH:            'Closing note (optional)',
    consultDeptOptional:      'Consult a department (optional)',
    noConsultation:           '— No consultation —',
    consultationNotify:       '{dept} will be notified with this note',
    sendConsultation:         'Send Consultation',
    taskNotFound:             'Task not found.',

    // SuperAdminPanel
    serviceNamePH:        'Service name',
    serviceDescPH:        'Short description (optional)',
    fieldsSuffix:         'fields',
    servicesCount:        '{n} services',
    servicesSectionTitle: 'Services / Transaction Types',
    addService:           'Add Service',
    serviceNameLabel:     'Service Name *',
    serviceNameExample:   'e.g. Marriage Allowance',
    serviceDescLabel:     'Description (optional)',
    serviceDescExample:   'Short description of the service',
    noServicesEmpty:      'No services — add a service to enable this department in the customer service interface',
    deptsSubtitle:        'Each department has services, and each service has its own fields',
    deptNameExample:      'e.g. Legal Affairs Department',

    // Users
    fullName:     'Full Name',
    email:        'Email',
    role:         'Role',
    deptAssign:   'Department',
    active:       'Active',
    inactive:     'Inactive',
    addUser:      '+ Add User',
    editUser:     'Edit User',
    newPassword:  'New Password (leave blank to keep current)',
    userCreated:  'User created.',
    userUpdated:  'User updated.',
    userDeleted:  'User deleted.',
    ldapUsers:          'Network Users (Active Directory)',
    ldapNotConfigured:  'LDAP service account not configured. Set LDAP_BIND_DN and LDAP_BIND_PASSWORD in the server .env file.',
    ldapTitle:          'Job Title',
    localUsers:         'Local Users',
    localUsersNote:     'Manually added accounts with password login',
    noLdapUsers:        'No users found in Active Directory.',
    noResults:          'No results found.',
    refresh:            'Refresh',
    assignRole:         'Assign Role',
    editRole:           'Edit Role',
    unassigned:         'No role assigned',
    ldapAssignTitle:    'Assign Role — Network User',
    roleAssigned:       'Role assigned.',
    rolesGuide:         'Roles Reference',
    rolesGuideNote:     'Assigned across all accounts (AD + local)',
    assigned:           'assigned',
    roleDesc: {
      SUPER_ADMIN:      'Sees and approves correspondence in every department, and manages users, departments and system settings. Intended for IT.',
      MANAGER:          'Approves or returns correspondence sent from their own department, and does everything an employee does. Requires a department.',
      ADMIN:            'The same authority as the department head, for that one department. Requires a department.',
      STAFF:            'Creates correspondence, edits and resends returned items, and marks incoming correspondence complete for their department. Requires a department.',
      READONLY:         'Can read their department\'s correspondence but cannot create it or act on it. Requires a department.',
      CUSTOMER_SERVICE: 'Legacy role from the retired task system. For correspondence it behaves exactly like an employee. Not offered for new assignments.',
    },
    deptHint:         'Sets which department this person sends correspondence from, and whose approval it needs.',
    deptOptionalHint: "Optional for this role — also adds the user to that department's chat and member list.",

    // Dashboard
    totalTasks:    'Total Tasks',
    openTasks:     'Open',
    closedTasks:   'Closed',
    returnedTasks: 'Returned',
    totalUsers:    'Total Users',
    byDept:        'Tasks by Department',
    recentTasks:   'Recent Tasks',
    noTasks:       'No tasks yet.',
    noUsers:       'No users yet.',


    overdue:           'Overdue',
    overdueTasks:      'Overdue Tasks',
    dueSoon:           'Due soon',
    tabAll:            'All',
    tabReturned:       'Returned',
    tabPending:        'To Send',
    tabWithDept:       'At Department',
    tabAwaitingReceipt:'Awaiting Receipt',
    tabInProgress:     'In Progress',
    tabClosed:         'Closed',
    duration:          'Duration',
    minSuffix:         'm',
    hourSuffix:        'h',
    daySuffix:         'd',
    customerServiceFallback: 'Customer Service',
    deptFallback:      'Department',
    notifications:     'Notifications',
    notifTitle:        'Doc Tracking',
    newMessagesCount:  '{n} new messages',
    newMessagesBatch:  '{n} new messages in {c} conversations',
    markAllRead:       'Mark all read',
    noNotifications:   'No notifications yet.',
    enableDesktopAlerts: 'Enable desktop alerts',
    search:            'Search…',
    roles: {
      SUPER_ADMIN:      'System Administrator',
      ADMIN:            'Deputy Department Head',
      CUSTOMER_SERVICE: 'Customer Service',
      MANAGER:          'Department Head',
      STAFF:            'Employee',
      READONLY:         'Read-only',
    },

    // التعاميم — organisation-wide circulars. Not part of t.corr: a تعميم has no
    // status, no routing and no approval, so sharing that namespace would mean
    // two features quietly reusing each other's wording.
    circulars: {
      deputy:   'Deputy Chairman Circular',
      director: 'Director General Circular',
      hint:     'Official circulars — everyone can read them; only the signing office publishes.',
      searchPlaceholder: 'Search title, text or circular number…',
      all: 'All', unreadOnly: 'Unread', from: 'From', to: 'To',
      clearFilters: 'Clear filters',
      empty: 'No circulars yet.',
      serial: 'Number', title: 'Title', publisher: 'Issued by', date: 'Date',
      name: 'Name', dept: 'Department', status: 'Status',
      attachments: 'Attachments', edited: 'Edited', new: 'New',
      newCircular: 'New circular', editCircular: 'Edit circular',
      publish: 'Publish', save: 'Save', edit: 'Edit', delete: 'Delete',
      deleteConfirm: 'Delete this circular permanently?',
      deleted: 'Circular deleted.', published: 'Circular published.', saved: 'Changes saved.',
      titleField: 'Circular title', bodyField: 'Circular text',
      titlePlaceholder: 'Subject of the circular',
      bodyPlaceholder: 'Write the circular text…',
      titleAndBodyRequired: 'Title and text are both required.',
      publishWarning: 'Once published, every employee sees this circular and is emailed about it.',
      readBy: 'Read by {n} of {total}', notReadYet: 'Not read yet',
      existingAttachments: '{n} attachment(s) already on this circular',
    },
    groupLabels: {
      board_office:                'Deputy Chairman Office',
      director_general_office:     'Director General Office',
      strategic_planning_dept:     'Strategic Planning & Projects',
      investments_dept:            'Endowment Investments',
      revenue_collection_dept:     'Revenue Collection',
      endowment_disbursement_dept: 'Endowment Disbursement & Development',
      sharia_studies_dept:         'Sharia Endowment & Studies',
      legal_affairs_dept:          'Legal Affairs & Endowment Properties',
      engineering_services_dept:   'Projects & Engineering Services',
      accounts_dept:               'Accounts',
      hr_dept:                     'Human Resources',
      procurement_dept:            'Procurement',
      it_dept:                     'Information Technology',
      admin_affairs_dept:          'Administrative Services',
      mosques_guidance_dept:       'Mosques & Religious Guidance',
      community_relations_dept:    'Communication & Customer Service',
      maintenance_dept:            'Maintenance',
      reception_dept:              'Reception',
      advisors_office:             'Advisors Office',
      legal_counsel_office:        'Administration Counsel',
      resources_information_dept:  'Resources & Information',
      other_dept:                  'Other',
    },

    // Messages / Chat
    corrNotifications: 'Correspondence',
    directory: {
      title: 'Staff Directory', count: '{n} people', showing: 'showing {n}',
      searchPlaceholder: 'Search: ahmed, أحمد, 5022…',
      message: 'Message', callExt: 'Call extension', online: 'Online',
      deptLines: '{dept} — direct lines',
      you: 'you', none: 'Nobody matches that search.',
      ext: 'Extension', mobile: 'Mobile', deptLine: 'Department line',
      altEmail: 'Additional email',
    },
    home: {
      needsYou: 'Needs you',
      needsYouHint: {
        staff:    'Correspondence only you can move on',
        approver: 'Waiting on your decision, or on your department',
        admin:    'Waiting on you, anywhere in the organisation',
      },
      kinds: {
        returned: 'Returned to you',
        approve:  'Waiting for your approval',
        complete: 'Addressed to your department',
      },
      waiting: '{n} d',
      allClear: 'Nothing is waiting on you',
      allClearHint: 'Everything addressed to you has been dealt with.',
      andMore: 'and {n} more',
      iSentOpen: 'Sent by me, still open',
      iSentDone: '{n} completed',
      deptIncoming: 'For my department',
      awaitingMe: 'Awaiting my approval',
      oldestWaiting: 'oldest {n} d',
      myDept: 'My department',
      deptSentOpen: 'Sent, still open',
      deptDone: 'Completed',
      systemHealth: 'System health',
      systemHealthHint: 'Things only IT can put right',
      systemOk: 'Nothing needs attention',
      systemOkHint: 'Every department has an approver and every account has a department.',
      noApprover: '{n} departments cannot approve anything',
      noDept: '{n} accounts have no department',
      noDeptHint: 'They cannot send correspondence until they do.',
    },
    usersAdmin: {
      title: 'System users',
      count: '{n} users', showing: 'showing {n}',
      searchPlaceholder: 'Search: ahmed, أحمد, email, ext…',
      allRoles: 'All roles', allDepts: 'All departments',
      noDeptFilter: 'No department', clearFilters: 'Clear filters',
      selectAll: 'Select everyone shown',
      selected: 'selected', clearSel: 'Clear',
      setRole: 'Set role…', setDept: 'Set department…', apply: 'Apply',
      activate: 'Activate', deactivate: 'Deactivate',
      bulkDone: '{n} users updated.',
      localTag: 'local',
      unassignedTitle: 'Active Directory accounts with no role',
      unassignedHint: 'Open to load from Active Directory',
      unassignedCount: '{n} accounts not yet in the system',
      allAssigned: 'Every Active Directory account already has a role.',
      extHint: '3 to 5 digits — this is what appears in the staff directory.',
      altEmailHint: 'A second address used for work, such as a personal Gmail. Shown in the directory beside the @swd.bh one.',
      itOnly: 'System administrator account — only IT can change this.',
      hrNote: 'You can set roles, departments, extensions and who is active. Creating and deleting accounts, and system administrator accounts, stay with IT.',
      auditTitle: 'Change history',
      auditHint: 'Every change made to a user account, and who made it',
      auditEmpty: 'No user changes recorded yet.',
      auditWhen: 'When', auditWho: 'Changed by', auditWhat: 'Action', auditDetail: 'Details',
      auditPeople: '{n} users',
      actions: {
        created: 'Account created', updated: 'Account edited', deleted: 'Account deleted',
        roleAssigned: 'Role assigned', bulkUpdated: 'Bulk change',
      },
    },
    corrDiscuss: 'Discuss in chat',
    corrDiscussNone: 'The other party has no account yet.',
    reports: {
      title: 'Reports', total: 'Total correspondence',
      avgApprove: 'Average approval time', avgApproveHint: 'from sending to the head\u2019s decision',
      avgDone: 'Average completion time',  avgDoneHint: 'from approval to completion',
      rejectRate: 'Return rate', rejectRateHint: 'returned at least once',
      byMonth: 'Correspondence per month',
      byDept: 'Busiest departments', byDeptHint: 'sent and received combined, top 8',
      byType: 'Most requested types', otherType: 'Other (free subject)',
      deptTable: 'By department', deptTableHint: 'sent versus received',
      sent: 'Sent', received: 'Received',
      backlog: 'Waiting longest', backlogHint: 'still awaiting approval, oldest first',
      waiting: 'Waiting', days: '{n} d',
      approvers: 'Approval activity', approversHint: 'decisions taken, and how long they took',
      approver: 'Approver', decisions: 'Decisions', avgTime: 'Average time',
      exportExcel: 'Export to Excel', noData: 'No data for this period.',
      ranges: { '30': 'Last 30 days', '90': 'Last 90 days', '365': 'Last year', all: 'All time' },
    },
    close: 'Close',
    skipToContent: 'Skip to main content',
    messages:          'Messages',
    newChat:           'New Conversation',
    searchPeople:      'Search people…',
    searchChats:       'Search chats and people…',
    people:            'People',
    noConversations:   'No conversations yet. Start one!',
    noMessagesYet:     'No messages yet. Say hello!',
    typeMessage:       'Type a message…',
    send:              'Send',
    attachFile:        'Attach a file',
    fileTooLarge:      'File is too large (max 15MB).',
    tooManyAttachments:'You can attach up to 10 files at a time.',
    attachmentPending: 'Ready to send — not sent yet',
    removeAttachment:  'Remove attachment',
    sending:           'Sending…',
    selectConversation:'Select a conversation to start messaging.',
    departmentGroup:   'Department group',
    deptThread:        'Private thread with the department',
    departmentsSection: 'Departments',
    peopleSection:      'People',
    groupChat:         'Group chat',
    members:           'Members',
    onlineNow:         '{n} online',
    startChat:         'Start chat',
    you:               'You',
    hideChat:          'Hide chat',
    unhideChat:        'Unhide chat',
    hiddenChats:       'Hidden chats',
    online:            'Online',
    away:              'Away',
    lastSeen:          'Last seen {time}',
    lastSeenNever:     'Offline',
    justNow:           'Just now',
    minAgo:            '{n}m ago',
    hourAgo:           '{n}h ago',
    dayAgo:            '{n}d ago',
    seen:              'Seen',
    seenBy:            'Seen by {names}',
    seenByAll:         'Seen by everyone',
    typingOne:         '{name} is typing…',
    typingMultiple:    'Several people are typing…',
    searchInChat:      'Search in conversation',
    noMatches:         'No matches',
    matchOf:           '{i} of {n}',
    enableNotifPrompt: 'Get notified when new messages arrive.',
    enableNotif:       'Enable',
    searchFilters:     'Filters',
    anySender:         'Any sender',
    fromDate:          'From date',
    toDate:            'To date',
    clearFilters:      'Clear filters',
    loadMoreResults:   'Load more results',
    notifSettings:     'Notification settings',
    notifDeniedHint:   'Notifications are blocked in your browser settings. Enable them for this site to use desktop alerts.',
    notifLevelMentionsDms:     'Mentions & direct messages',
    notifLevelMentionsDmsHint: 'Recommended — notify for DMs, group chats, and @mentions only. Stays quiet during regular department-channel chatter.',
    notifLevelAll:             'All messages',
    notifLevelAllHint:         'Notify for every new message in every conversation, including department channels.',
    notifLevelOff:             'Off',
    notifLevelOffHint:         'No desktop notifications. You will still see unread badges in the app.',
    messagesResults:   'Messages',
    addReaction:       'Add reaction',
    moreReactions:     'More emoji',
    emojiGroups: { common: 'Common', faces: 'Faces', work: 'Work', signals: 'Signals' },
    mentionedYou:      'mentioned you',
    reply:             'Reply',
    cancelReply:       'Cancel reply',
    attachment:        'Attachment',
    pin:               'Pin to top',
    unpin:             'Unpin',
    pinnedBy:          'Pinned by {name}',
    setStatus:         'Set status',
    statusPlaceholder: 'What are you up to?',
    clearStatus:       'Clear status',
    statusPresets: ['In a meeting', 'On leave', 'Out of office', 'Be right back'],
    profilePicture: 'Profile picture',
    uploadPicture:  'Upload picture',
    removePicture:  'Remove',
    avatarColor:    'Avatar color',

    // ── نظام المراسلات الداخلية — internal correspondence ──
    deptGroupOffices: 'Offices',
    deptGroupDepts:   'Departments',
    deptSearchPlaceholder: 'Search for a department…',
    noDept: 'No department',
    fromDeptsLabel: 'Which departments may request this service?',
    toDeptsLabel:   'Which departments receive this?',
    fromDeptsAll:   'All departments',
    fromDeptsSome:  'restricted to {n} department(s)',
    dirRequest:     'Incoming',
    dirIssue:       'Outgoing',
    dirLabel:       'Direction',
    dirRequestHint: 'Something this department receives',
    dirIssueHint:   'Something this department sends out',
    corr: {
      title: 'Internal Correspondence',
      nav: { correspondence: 'Correspondence', dashboard: 'Correspondence board', new: 'New correspondence',
             inbox: 'Inbox', approvals: 'Approvals', returned: 'Returned to me', archive: 'Archive' },
      statuses:   { pending: 'Awaiting approval', approved: 'Approved', done: 'Completed', returned: 'Returned for review' },
      priorities: { high: 'High', med: 'Medium', low: 'Low' },
      events: { created: 'Created', approved: 'Approved by department head', rejected: 'Returned for review',
                resubmitted: 'Edited and resubmitted', reply: 'Reply', completed: 'Completed' },
      reply: {
        label: 'Write a reply', placeholder: 'Write your reply…',
        send: 'Send reply', sent: 'Reply sent.',
        needText: 'Write a reply or attach a file.',
        withYou: 'Waiting on your department', withThem: 'Waiting on {dept}',
        closedHint: 'Only the sender or their department head can complete this.',
      },
      tiles: { total: 'Total correspondence', pending: 'Awaiting approval', done: 'Completed',
               approved: 'In progress', returned: 'Returned for review' },
      boxHints: { inbox: 'Addressed to your department', approvals: 'Pending items from your own department',
                  returned: 'Sent back to you with a reason', archive: 'Everything you can see' },
      emptyBox: { inbox: 'Nothing in your inbox.', approvals: 'Nothing waiting on your approval.',
                  returned: 'Nothing has been returned to you.', archive: 'No correspondence yet.' },
      willBeSentTo: 'Goes to {name} for approval',
      approverOnline: 'online now', approverAway: 'last seen {when}', approverNoAccount: 'no account yet',
      headRole: 'Department head', deputyRole: 'Deputy',
      noApproverYet: 'No department head is set for your department yet — a system administrator will approve.',
      addFiles: 'Add files', charCount: '{n} characters',
      toastApproved: 'Correspondence approved.',
      toastRejected: 'Returned to the employee with your reason.',
      toastCompleted: 'Marked as completed.',
      newTitle: 'New correspondence', newSubtitle: 'Goes to your department head for approval before it is sent.',
      editReturnedTitle: 'Edit returned correspondence',
      editingNotice: 'You are editing a returned item.',
      recentTitle: 'Most recent',
      serial: 'Reference', subject: 'Subject', sender: 'Sender', fromDept: 'Sending department',
      toDept: 'Receiving department', date: 'Date', priority: 'Priority', status: 'Status',
      body: 'Message text', attachments: 'Attachments', timeline: 'Approval history',
      requestType: 'Subject', other: 'Other (type your own subject)',
      svcWeIssue: 'What we send them', svcTheyAccept: 'What we ask them for',
      subjectPlaceholder: 'Write the subject', bodyPlaceholder: 'Write the message',
      choose: 'Choose…', pickDeptFirst: 'Pick the receiving department first',
      all: 'All', searchPlaceholder: 'Search subject or reference…',
      send: 'Send', resubmit: 'Save and resend', approve: 'Approve', reject: 'Reject and return',
      complete: 'Mark completed', viewDetails: 'View details', editResend: 'Edit and resend',
      reviewIt: 'Review', removeFile: 'Remove file',
      rejectModalTitle: 'Reason for rejection', rejectReason: 'Reason for return',
      rejectReasonPlaceholder: 'Explain what needs to change', rejectConfirm: 'Return to employee',
      dropHint: 'Drag files here, or click to browse', dropLimit: 'Up to 10MB per file',
      existingAttachments: '{n} attachment(s) already on this correspondence',
      sentToHead: 'Sent to the department head for approval.',
      resubmitted: 'Resent to the department head.',
      tooBig: 'File "{name}" is larger than 10MB.', dupFile: 'File "{name}" is already attached.',
      errToDept: 'Choose a receiving department.', errType: 'Choose a request type.',
      errSubject: 'Subject is required.', errBody: 'Message text is required.',
      errReason: 'A reason is required.',
      noDeptTitle: 'No department assigned',
      noDeptBody: 'Your account has no department, so correspondence cannot be sent from it. Please contact the system administrator.',
      print: { button: 'Print', kingdom: 'Kingdom of Bahrain',
               administration: 'General Administration for Sunni Affairs',
               systemName: 'Internal Correspondence System', refNo: 'Reference number',
               bismillah: 'In the name of God, the Most Gracious, the Most Merciful',
               officialMemo: 'Official internal correspondence', messrs: 'Messrs',
               mayGodProtect: 'may God protect you,,,', greeting: 'Peace be upon you and God\u2019s mercy and blessings,',
               closing: 'Please accept our highest regards and appreciation,,,', printedOn: 'Printed on' },
    },
  },

  ar: {
    appName:    'نظام تتبع الوثائق',
    orgName:    'الإدارة العامة للأوقاف السنية',
    loginSubtitle: 'أدخل بيانات حساب المؤسسة',
    loginFeatures: [
      'تتبع المراسلات الرسمية الصادرة والواردة',
      'إدارة الاستفسارات وطلبات الجمهور',
      'متابعة العقود والشيكات والبحوث الاجتماعية',
      'لوحة إدارة متكاملة مع صلاحيات LDAP',
    ],
    signIn:     'تسجيل الدخول',
    signOut:    'خروج',
    signingIn:  'جاري الدخول…',
    username:   'اسم المستخدم',
    password:   'كلمة المرور',
    usernamePH: 'اسم المستخدم أو البريد الإلكتروني',
    welcome:    'مرحباً',
    dept:       'القسم',
    adminPanel: 'الإعدادات',
    loading:    'جاري التحميل…',
    na:         'غير محدد',
    departments:'الأقسام',
    newRecord:  'سجل جديد',
    submit:     'إرسال',
    reset:      'إعادة تعيين',
    required:   'مطلوب',
    save:       'حفظ',
    cancel:     'إلغاء',
    edit:       'تعديل',
    del:        'حذف',
    add:        'إضافة',
    confirmDel: 'هل أنت متأكد؟ لا يمكن التراجع.',
    selectDept: 'اختر قسماً من القائمة الجانبية للبدء.',
    submitted:  'تم الإرسال بنجاح.',
    deptFields:       'الأقسام',
    roleMaps:         'الأدوار التلقائية (AD)',
    config:           'النسخ الاحتياطي',
    addDept:          'إضافة قسم',
    deptLabel:        'اسم القسم',
    adGroup:          'مجموعة AD (اختياري)',
    adGroupHint:      'اسم CN لمجموعة Active Directory المرتبطة بهذا القسم (يُستخدم لتوجيه المهام تلقائياً).',
    fields:           'حقل',
    addField:         '+ إضافة حقل',
    fieldKey:         'مفتاح الحقل',
    fieldLabel:       'التسمية',
    fieldType:        'النوع',
    fieldReq:         'مطلوب',
    optionsPH:        'خيار1، خيار2، خيار3',
    actions:          'الإجراءات',
    optPH:            'الخيارات / النص التوضيحي',
    exportJSON:       'تنزيل نسخة احتياطية',
    previewCfg:       'معاينة',
    importCfg:        'استيراد وتطبيق',
    importPH:         '{"departments": [...], "roleGroupMap": {...}}',
    importNote:       'الصق JSON للاستعادة (يستبدل جميع الأقسام وتعيينات الأدوار):',
    cfgNote:          'قم بتنزيل نسخة احتياطية من إعدادات الأقسام والأدوار، أو الاستعادة من نسخة سابقة.',
    ldapNote:         'عند تسجيل دخول مستخدم AD دون دور محدد يدوياً، يُعيَّن الدور تلقائياً بناءً على عضوية المجموعة. أضف اسم CN واختر الدور.',
    adAutoRolesNote:  'تُطبَّق هذه القواعد تلقائياً عند تسجيل الدخول. لتعيين الأدوار يدوياً لكل شخص، استخدم صفحة المستخدمين.',
    roleMap:          'مجموعة AD ← الدور التلقائي',
    newGroup:         'اسم_المجموعة_cn',
    deptNote:         'تظهر الأقسام فوراً في جميع القوائم المنسدلة (المستخدمون، إنشاء المهام) بعد الحفظ.',
    usersInDept:      'مستخدم',
    advancedOptions:  'خيارات متقدمة',
    customFields:     'الحقول المخصصة',
    customFieldsNote: 'حقول إضافية تظهر عند إنشاء مهمة لهذا القسم.',
    noDepts:          'لا توجد أقسام بعد. أضف قسماً للبدء.',

    // Bulk actions
    selectAll:        'تحديد الكل',
    selected:         'محدد',
    bulkForward:      'إحالة الكل',
    bulkClose:        'إغلاق الكل',
    clearSelection:   'إلغاء',
    bulkDone:         'تم — {n} مهام محدّثة.',
    selectDeptBulk:   'إحالة {n} مهام إلى:',

    // Task templates
    templates:        'القوالب',
    templateName:     'اسم القالب',
    useTemplate:      'استخدام قالب',
    noTemplate:       'بدون قالب',
    addTemplate:      'إضافة قالب',
    editTemplate:     'تعديل القالب',
    templateSaved:    'تم حفظ القالب.',
    templateDeleted:  'تم حذف القالب.',
    noTemplates:      'لا توجد قوالب بعد.',
    expectedDays:     'الأيام المتوقعة',
    templatesNote:    'قوالب لملء حقول المهام مسبقاً. متاحة لجميع الموظفين عند إنشاء مهمة.',

    // Sessions
    activeSessions:   'الجلسات النشطة',
    sessionsNote:     'جميع المستخدمين الذين سجلوا الدخول حالياً. إنهاء الجلسة يُبطل صلاحيتهم فوراً.',
    forceLogout:      'إنهاء الجلسة',
    sessionTerminated:'تم إنهاء الجلسة.',
    noSessions:       'لا توجد جلسات نشطة.',
    loggedInAt:       'دخل في',
    expiresAt:        'تنتهي في',
    yourSession:      'أنت',

    // Audit log
    auditLog:         'سجل المراقبة',
    auditActor:       'المستخدم',
    auditAction:      'الإجراء',
    auditTarget:      'الهدف',
    auditTime:        'الوقت',
    auditFilter:      'تصفية بالمستخدم…',
    noAuditLogs:      'لا توجد سجلات.',
    auditActions: {
      USER_LOGIN:          'تسجيل دخول',
      USER_LOGOUT:         'تسجيل خروج',
      TASK_CREATED:        'إنشاء مهمة',
      TASK_FORWARDED:      'إحالة مهمة',
      TASK_CLOSED:         'إغلاق مهمة',
      USER_CREATED:        'إنشاء مستخدم',
      USER_UPDATED:        'تحديث مستخدم',
      USER_DELETED:        'حذف مستخدم',
      LDAP_ROLE_ASSIGNED:  'تعيين دور',
      SESSION_TERMINATED:  'إنهاء جلسة',
    },

    // Dashboard dept filter
    allDepartments:   'جميع الأقسام',
    viewingDept:      'عرض:',
    deptStats:        'إحصائيات القسم',

    // Navigation
    dashboard:  'لوحة المتابعة',
    tasks:      'المهام',
    comingSoon:      'قريبًا.',
    exportCSV:       'تصدير CSV',
    showOriginal:    'عرض النص الأصلي',
    showTranslation: 'عرض الترجمة',
    translate:       'ترجمة',
    translating:     'جارٍ الترجمة…',
    translateFailed: 'فشلت الترجمة. حاول مرة أخرى.',
    translateChat:   'ترجمة هذه المحادثة',
    translateChatOn: 'جارٍ ترجمة المحادثة',
    reassignTask:    'إعادة توجيه المهمة',
    reassignExplain: 'انقل هذه المهمة مباشرةً إلى قسم آخر دون إعادتها إلى الاستقبال.',
    reassignNotePH:  'سبب إعادة التوجيه (اختياري)…',
    taskReassigned:  'تمت إعادة توجيه المهمة بنجاح.',
    recentSenders:   'مراسلون سابقون',
    deptQueue:       'قائمة انتظار القسم',
    deptQueueEmpty:  'لا توجد مهام مفتوحة معيّنة لقسمك.',
    idleDays:        '{n} يوم بدون تحديث',
    idleLabel:       'بدون تحديث',
    priorityUpdated: 'تم تحديث الأولوية.',
    escalatePriorityHint: 'انقر لتغيير الأولوية',
    snooze2h:        'تأجيل ساعتين',
    allSnoozed:      'تم تأجيل جميع التذكيرات.',
    taskCategory:    'التصنيف',
    allCategories:   'الكل',
    catWork:         'عمل',
    catPersonal:     'شخصي',
    catFollowUp:     'متابعة',
    allTasks:   'جميع المهام',
    users:      'المستخدمون',
    settings:   'إعدادات النظام',
    deptForms:  'نماذج الأقسام',

    // Task workflow
    createTask:     'إنشاء مهمة',
    taskTitle:      'عنوان المهمة',
    taskType:       'النوع',
    taskPriority:   'الأولوية',
    taskStatus:     'الحالة',
    taskSerial:     'الرقم التسلسلي',
    taskCreated:    'تاريخ الإنشاء',
    taskAssigned:   'محال إلى',
    taskSource:     'الجهة المرسلة',
    taskDelivery:   'طريقة الاستلام',
    taskExpected:   'تاريخ الإنجاز المتوقع',
    taskCompleted:  'تاريخ الإنجاز الفعلي',
    taskNote:       'ملاحظات',
    forwardTask:    'إحالة إلى قسم',
    returnToCS:     'إرجاع لخدمة العملاء',
    closeTask:      'إغلاق المهمة',
    addComment:     'إضافة تعليق',
    markReceived:   'تم الاستلام',
    receivedAdded:  'تم تسجيل الاستلام.',
    taskHistory:    'سجل النشاط',
    selectDeptFwd:  'اختر القسم المحال إليه',
    confirmClose:   'هل تريد إغلاق هذه المهمة؟',
    confirmReturn:  'هل تريد إرجاع المهمة إلى خدمة العملاء؟',
    taskClosed:     'تم إغلاق المهمة.',
    taskForwarded:  'تم إحالة المهمة.',
    taskReturned:   'تم إرجاع المهمة لخدمة العملاء.',
    commentAdded:   'تمت إضافة التعليق.',

    types:     { incoming: 'وارد', outgoing: 'صادر' },
    priorities:{ low: 'منخفضة', normal: 'عادية', high: 'عالية', urgent: 'عاجلة' },
    statuses:  { new: 'جديدة', assigned: 'محالة', in_progress: 'قيد التنفيذ', returned: 'مُرجَعة', closed: 'مغلقة' },
    eventTypes:{
      created:   'تم إنشاء المهمة',
      forwarded: 'أُحيلت إلى',
      returned:  'أُرجعت لخدمة العملاء',
      commented: 'تعليق',
      closed:    'تم الإغلاق',
    },

    // Create Task — CS wizard
    createTransaction:    'إنشاء معاملة جديدة',
    senderTypePerson:     'شخص',
    senderTypeCompany:    'شركة',
    senderTypeOther:      'أخرى',
    senderInfoLabel:      'معلومات المُراجع',
    enterSenderInfo:      'أدخل معلومات الجهة أو الشخص المُراجع',
    senderLabel:          'الجهة المرسلة',
    companyOrEntityName:  'اسم الشركة / الجهة',
    phoneNumber:          'رقم الهاتف',
    chooseDeptForTask:    'اختر الإدارة المعنية بالمعاملة',
    chooseDeptPH:         'اختر الإدارة',
    nServices:            '{n} خدمة',
    backToDepts:          'الإدارات',
    chooseServiceType:    'اختر نوع الخدمة',
    noServicesForDept:    'لا توجد خدمات مضافة لهذه الإدارة',
    reviewerLabel:        'المُراجع:',
    changeBtn:             'تغيير',
    noFieldsForService:   'لا توجد حقول لهذه الخدمة — سيتم إنشاء المعاملة مباشرة',
    nextBtn:              'التالي',
    backBtn:              'رجوع',
    selectOptionPH:       '— اختر —',
    searchServicePH:      'ابحث عن خدمة أو إدارة...',
    formAutoSentToCS:     'سيتم إرسال النموذج تلقائياً إلى خدمة العملاء',
    formAutoSentToCSNote: 'سيتم إرسال هذا النموذج تلقائياً إلى خدمة العملاء · جميع الحقول الإلزامية مُعلّمة بـ *',
    changeType:           'تغيير النوع',
    deliveryManual:       'يدوي',
    deliveryMail:         'بريد',
    deliveryEmail:        'إيميل',
    deliveryFax:          'فاكس',
    deliveryOther:        'أخرى',

    // Task detail
    returnedFromDeptBanner:   'مُعاد من القسم — بانتظار مراجعة خدمة العملاء',
    atCSNotSentBanner:        'عند خدمة العملاء — لم يُرسل بعد',
    inProgressAtDept:         'قيد التنفيذ عند {dept}',
    sentAwaitingReceipt:      'أُرسلت إلى {dept} — بانتظار الاستلام',
    cycleSuffix:              'دورة',
    confirmReceived:          'تم تأكيد الاستلام',
    acceptStart:              'قبول / بدء التنفيذ',
    senderLabelField:         'الجهة المرسلة',
    nameField:                'الاسم',
    phoneField:               'الهاتف',
    yesValue:                 '✓ نعم',
    noValue:                  '✗ لا',
    cyclesNote:               'دورة إرسال وإرجاع',
    cycleLabel:               'دورة {n}',
    eventCreated:             'تم الإنشاء',
    eventForwardedTo:         'أُرسل إلى',
    eventReturnedToCS:        'أُعيد إلى خدمة العملاء',
    eventAcceptedStarted:     'تم الاستلام / بدء التنفيذ',
    eventCommented:           'ملاحظة',
    eventConsultation:        'استشارة →',
    eventClosed:              'تم الإغلاق',
    consultationTag:          'استشارة',
    fromDeptLabel:            'من {dept}',
    selectDeptPH:             '— اختر الإدارة —',
    notePHForDept:            'ملاحظة للقسم…',
    returnExplain:            'سيتم إرجاع المعاملة إلى خدمة العملاء للمراجعة. أضف ملاحظة توضح ما تم إنجازه.',
    returnNotePH:             'ما الذي تم إنجازه؟ هل هناك متابعة مطلوبة؟',
    closeConfirmReturned:     'تمت مراجعة المعاملة المُعادة — هل تريد إغلاقها نهائياً؟',
    closeConfirmDefault:      'هل أنت متأكد من إغلاق هذه المعاملة نهائياً؟',
    closingNotePH:            'ملاحظة ختامية (اختياري)',
    consultDeptOptional:      'استشارة قسم (اختياري)',
    noConsultation:           '— بدون استشارة —',
    consultationNotify:       'سيتم إشعار {dept} بهذه الملاحظة',
    sendConsultation:         'إرسال استشارة',
    taskNotFound:             'المعاملة غير موجودة.',

    // SuperAdminPanel
    serviceNamePH:        'اسم الخدمة',
    serviceDescPH:        'وصف مختصر (اختياري)',
    fieldsSuffix:         'حقول',
    servicesCount:        '{n} خدمة',
    servicesSectionTitle: 'الخدمات / أنواع المعاملات',
    addService:           'إضافة خدمة',
    serviceNameLabel:     'اسم الخدمة *',
    serviceNameExample:   'مثال: إعانة زواج',
    serviceDescLabel:     'الوصف (اختياري)',
    serviceDescExample:   'وصف مختصر للخدمة',
    noServicesEmpty:      'لا توجد خدمات — أضف خدمة لتفعيل هذه الإدارة في واجهة خدمة العملاء',
    deptsSubtitle:        'كل إدارة تحتوي على خدمات، وكل خدمة تحتوي على حقول خاصة بها',
    deptNameExample:      'مثال: قسم الشؤون القانونية',

    // Users
    fullName:     'الاسم الكامل',
    email:        'البريد الإلكتروني',
    role:         'الدور',
    deptAssign:   'القسم',
    active:       'نشط',
    inactive:     'غير نشط',
    addUser:      '+ إضافة مستخدم',
    editUser:     'تعديل المستخدم',
    newPassword:  'كلمة مرور جديدة (اتركها فارغة للإبقاء على الحالية)',
    userCreated:  'تم إنشاء المستخدم.',
    userUpdated:  'تم تحديث المستخدم.',
    userDeleted:  'تم حذف المستخدم.',
    ldapUsers:          'مستخدمو الشبكة (Active Directory)',
    ldapNotConfigured:  'لم يتم تكوين حساب خدمة LDAP. أضف LDAP_BIND_DN و LDAP_BIND_PASSWORD في ملف .env الخاص بالخادم.',
    ldapTitle:          'المسمى الوظيفي',
    localUsers:         'المستخدمون المحليون',
    localUsersNote:     'حسابات مضافة يدوياً بكلمة مرور',
    noLdapUsers:        'لم يتم العثور على مستخدمين في Active Directory.',
    noResults:          'لا توجد نتائج.',
    refresh:            'تحديث',
    assignRole:         'تعيين دور',
    editRole:           'تعديل الدور',
    unassigned:         'لم يُعيَّن دور',
    ldapAssignTitle:    'تعيين دور — مستخدم الشبكة',
    roleAssigned:       'تم تعيين الدور.',
    rolesGuide:         'دليل الأدوار',
    rolesGuideNote:     'الأدوار المُعيَّنة في جميع الحسابات (الشبكة + المحلية)',
    assigned:           'مُعيَّن',
    roleDesc: {
      SUPER_ADMIN:      'يطّلع على مراسلات جميع الأقسام ويوافق عليها، ويدير المستخدمين والأقسام وإعدادات النظام. مخصّص لتقنية المعلومات.',
      MANAGER:          'يوافق على المراسلات الصادرة من قسمه أو يعيدها للمراجعة، ويقوم بكل ما يقوم به الموظف. يشترط تعيين القسم.',
      ADMIN:            'نفس صلاحيات رئيس القسم، ولهذا القسم وحده. يشترط تعيين القسم.',
      STAFF:            'ينشئ المراسلات، ويعدّل المُعادة منها ويعيد إرسالها، ويسجّل إنجاز المراسلات الواردة إلى قسمه. يشترط تعيين القسم.',
      READONLY:         'يطّلع على مراسلات قسمه دون إنشائها أو اتخاذ أي إجراء عليها. يشترط تعيين القسم.',
      CUSTOMER_SERVICE: 'دور قديم من نظام المهام المتوقف. يعمل كالموظف تماماً في المراسلات. غير متاح للتعيينات الجديدة.',
    },
    deptHint:         'يحدد القسم الذي يُرسل هذا الشخص المراسلات باسمه، ومن يوافق عليها.',
    deptOptionalHint: 'اختياري لهذا الدور — يضيف المستخدم أيضاً إلى محادثة هذا القسم وقائمة أعضائه.',

    // Dashboard
    totalTasks:    'إجمالي المهام',
    openTasks:     'مفتوحة',
    closedTasks:   'مغلقة',
    returnedTasks: 'مُرجَعة',
    totalUsers:    'المستخدمون',
    byDept:        'المهام حسب القسم',
    recentTasks:   'أحدث المهام',
    noTasks:       'لا توجد مهام بعد.',
    noUsers:       'لا يوجد مستخدمون بعد.',


    overdue:           'متأخرة',
    overdueTasks:      'المهام المتأخرة',
    dueSoon:           'قريبة الاستحقاق',
    tabAll:            'الكل',
    tabReturned:       'مُعادة',
    tabPending:        'للإرسال',
    tabWithDept:       'عند القسم',
    tabAwaitingReceipt:'بانتظار الاستلام',
    tabInProgress:     'قيد التنفيذ',
    tabClosed:         'مغلقة',
    duration:          'المدة',
    minSuffix:         'د',
    hourSuffix:        'س',
    daySuffix:         'يوم',
    customerServiceFallback: 'خدمة العملاء',
    deptFallback:      'القسم',
    notifications:     'الإشعارات',
    notifTitle:        'نظام تتبع الوثائق',
    newMessagesCount:  '{n} رسائل جديدة',
    newMessagesBatch:  '{n} رسائل جديدة في {c} محادثات',
    markAllRead:       'تعليم الكل كمقروء',
    noNotifications:   'لا توجد إشعارات بعد.',
    enableDesktopAlerts: 'تفعيل تنبيهات سطح المكتب',
    search:            'بحث…',
    roles: {
      SUPER_ADMIN:      'مدير النظام',
      ADMIN:            'نائب رئيس القسم',
      CUSTOMER_SERVICE: 'خدمة العملاء',
      MANAGER:          'رئيس القسم',
      STAFF:            'موظف',
      READONLY:         'قراءة فقط',
    },

    // التعاميم — تعميم رسمي يقرأه الجميع ويصدره المكتب المختص. مفصول عن t.corr
    // لأن التعميم بلا حالة ولا توجيه ولا موافقة.
    circulars: {
      deputy:   'تعميم نائب الرئيس',
      director: 'تعميم المدير العام',
      hint:     'التعاميم الرسمية — يطّلع عليها جميع الموظفين، ويصدرها المكتب المختص.',
      searchPlaceholder: 'ابحث في العنوان أو النص أو رقم التعميم…',
      all: 'الكل', unreadOnly: 'غير المقروءة', from: 'من', to: 'إلى',
      clearFilters: 'إزالة عوامل التصفية',
      empty: 'لا توجد تعاميم بعد.',
      serial: 'رقم التعميم', title: 'العنوان', publisher: 'أصدره', date: 'التاريخ',
      name: 'الاسم', dept: 'القسم', status: 'الحالة',
      attachments: 'المرفقات', edited: 'مُعدّل', new: 'جديد',
      newCircular: 'تعميم جديد', editCircular: 'تعديل التعميم',
      publish: 'إصدار التعميم', save: 'حفظ', edit: 'تعديل', delete: 'حذف',
      deleteConfirm: 'حذف هذا التعميم نهائياً؟',
      deleted: 'تم حذف التعميم.', published: 'تم إصدار التعميم.', saved: 'تم حفظ التعديلات.',
      titleField: 'عنوان التعميم', bodyField: 'نص التعميم',
      titlePlaceholder: 'موضوع التعميم',
      bodyPlaceholder: 'اكتب نص التعميم…',
      titleAndBodyRequired: 'العنوان والنص مطلوبان.',
      publishWarning: 'بعد الإصدار سيظهر التعميم لجميع الموظفين وسيصلهم إشعار بالبريد.',
      readBy: 'قرأه {n} من {total}', notReadYet: 'لم يقرأه بعد',
      existingAttachments: 'يوجد {n} مرفق على هذا التعميم',
    },
    groupLabels: {
      board_office:                'مكتب نائب الرئيس',
      director_general_office:     'مكتب المدير العام',
      strategic_planning_dept:     'قسم التخطيط الاستراتيجي ومتابعة المشاريع الوقفية',
      investments_dept:            'قسم الاستثمارات الوقفية',
      revenue_collection_dept:     'قسم تحصيل الإيرادات',
      endowment_disbursement_dept: 'قسم المصارف الوقفية وتنمية الوقف',
      sharia_studies_dept:         'قسم الوقف الشرعي والدراسات',
      legal_affairs_dept:          'قسم الشؤون القانونية والأملاك الوقفية',
      engineering_services_dept:   'قسم المشاريع والخدمات الهندسية',
      accounts_dept:               'قسم الحسابات',
      hr_dept:                     'قسم الموارد البشرية',
      procurement_dept:            'قسم المشتريات',
      it_dept:                     'قسم تقنية المعلومات',
      admin_affairs_dept:          'قسم الخدمات الإدارية',
      mosques_guidance_dept:       'قسم المساجد والإرشاد الديني',
      community_relations_dept:    'قسم الاتصال وخدمة العملاء',
      maintenance_dept:            'قسم الصيانة',
      reception_dept:              'قسم الاستقبال',
      advisors_office:             'مكتب المستشارين',
      legal_counsel_office:        'محامي الإدارة',
      resources_information_dept:  'قسم الموارد والمعلومات',
      other_dept:                  'أخرى',
    },

    // Messages / Chat
    corrNotifications: 'المراسلات',
    directory: {
      title: 'دليل الهاتف', count: '{n} موظفاً', showing: 'المعروض {n}',
      searchPlaceholder: 'ابحث: أحمد، ahmed، 5022…',
      message: 'محادثة', callExt: 'اتصال بالرقم الداخلي', online: 'متصل الآن',
      deptLines: '{dept} — خطوط مباشرة',
      you: 'أنت', none: 'لا يوجد من يطابق البحث.',
      ext: 'الرقم الداخلي', mobile: 'الجوال', deptLine: 'خط القسم',
      altEmail: 'بريد إضافي',
    },
    home: {
      needsYou: 'يحتاج إجراءً منك',
      needsYouHint: {
        staff:    'مراسلات لا يستطيع تحريكها سواك',
        approver: 'بانتظار قرارك، أو بانتظار قسمك',
        admin:    'بانتظارك، في أي قسم من الإدارة',
      },
      kinds: {
        returned: 'مُعادة إليك',
        approve:  'بانتظار موافقتك',
        complete: 'موجّهة إلى قسمك',
      },
      waiting: '{n} ي',
      allClear: 'لا شيء ينتظرك',
      allClearHint: 'كل ما وُجّه إليك تم التعامل معه.',
      andMore: 'و{n} أخرى',
      iSentOpen: 'أرسلتها ولم تُغلق',
      iSentDone: 'أُنجزت {n}',
      deptIncoming: 'واردة إلى قسمي',
      awaitingMe: 'بانتظار موافقتي',
      oldestWaiting: 'أقدمها {n} ي',
      myDept: 'قسمي',
      deptSentOpen: 'مُرسلة ولم تُغلق',
      deptDone: 'مُنجزة',
      systemHealth: 'حالة النظام',
      systemHealthHint: 'أمور لا يصلحها إلا قسم تقنية المعلومات',
      systemOk: 'لا يوجد ما يحتاج إلى انتباه',
      systemOkHint: 'كل قسم لديه من يعتمد، وكل حساب مرتبط بقسم.',
      noApprover: '{n} أقسام لا تستطيع اعتماد أي مراسلة',
      noDept: '{n} حسابات بلا قسم',
      noDeptHint: 'لا يمكنها إرسال المراسلات حتى تُربط بقسم.',
    },
    usersAdmin: {
      title: 'مستخدمو النظام',
      count: '{n} مستخدماً', showing: 'المعروض {n}',
      searchPlaceholder: 'ابحث: أحمد، ahmed، البريد، الرقم…',
      allRoles: 'كل الصلاحيات', allDepts: 'كل الأقسام',
      noDeptFilter: 'بدون قسم', clearFilters: 'إلغاء التصفية',
      selectAll: 'تحديد كل المعروض',
      selected: 'محدد', clearSel: 'إلغاء التحديد',
      setRole: 'تعيين الصلاحية…', setDept: 'تعيين القسم…', apply: 'تطبيق',
      activate: 'تفعيل', deactivate: 'إيقاف',
      bulkDone: 'تم تحديث {n} مستخدماً.',
      localTag: 'محلي',
      unassignedTitle: 'حسابات في الشبكة بدون صلاحية',
      unassignedCount: '{n} حساباً غير مضاف إلى النظام',
      unassignedHint: 'افتح لتحميلها من الشبكة',
      allAssigned: 'جميع حسابات الشبكة لها صلاحية.',
      extHint: 'من ٣ إلى ٥ أرقام — هذا ما يظهر في دليل الهاتف.',
      altEmailHint: 'عنوان ثانٍ يُستخدم للعمل، مثل بريد Gmail شخصي. يظهر في دليل الهاتف بجانب بريد @swd.bh.',
      itOnly: 'حساب مدير نظام — لا يعدّله إلا قسم تقنية المعلومات.',
      hrNote: 'يمكنك تعيين الصلاحيات والأقسام والأرقام الداخلية وتفعيل الحسابات أو إيقافها. أما إنشاء الحسابات وحذفها وحسابات مدير النظام فتبقى لدى تقنية المعلومات.',
      auditTitle: 'سجل التغييرات',
      auditHint: 'كل تغيير جرى على حسابات المستخدمين، ومن قام به',
      auditEmpty: 'لا توجد تغييرات مسجلة بعد.',
      auditWhen: 'التاريخ', auditWho: 'بواسطة', auditWhat: 'الإجراء', auditDetail: 'التفاصيل',
      auditPeople: '{n} مستخدماً',
      actions: {
        created: 'إنشاء حساب', updated: 'تعديل حساب', deleted: 'حذف حساب',
        roleAssigned: 'تعيين صلاحية', bulkUpdated: 'تعديل جماعي',
      },
    },
    corrDiscuss: 'ناقش في المحادثات',
    corrDiscussNone: 'لا يوجد حساب مرتبط بالطرف الآخر بعد.',
    reports: {
      title: 'التقارير', total: 'إجمالي المراسلات',
      avgApprove: 'متوسط زمن الموافقة', avgApproveHint: 'من الإرسال حتى قرار رئيس القسم',
      avgDone: 'متوسط زمن الإنجاز',      avgDoneHint: 'من الموافقة حتى الإنجاز',
      rejectRate: 'نسبة الإعادة', rejectRateHint: 'أُعيدت مرة واحدة على الأقل',
      byMonth: 'المراسلات شهرياً',
      byDept: 'أكثر الأقسام نشاطاً', byDeptHint: 'الصادر والوارد معاً، أعلى ٨',
      byType: 'أكثر أنواع الطلبات', otherType: 'أخرى (موضوع حر)',
      deptTable: 'حسب القسم', deptTableHint: 'الصادر مقابل الوارد',
      sent: 'صادر', received: 'وارد',
      backlog: 'الأطول انتظاراً', backlogHint: 'ما زالت بانتظار الموافقة، الأقدم أولاً',
      waiting: 'مدة الانتظار', days: '{n} يوم',
      approvers: 'نشاط الموافقات', approversHint: 'القرارات المتخذة والزمن المستغرق',
      approver: 'المعتمِد', decisions: 'القرارات', avgTime: 'متوسط الزمن',
      exportExcel: 'تصدير إلى Excel', noData: 'لا توجد بيانات لهذه الفترة.',
      ranges: { '30': 'آخر ٣٠ يوماً', '90': 'آخر ٩٠ يوماً', '365': 'آخر سنة', all: 'كل الفترات' },
    },
    close: 'إغلاق',
    skipToContent: 'تخطَّ إلى المحتوى',
    messages:          'المحادثات',
    newChat:           'محادثة جديدة',
    searchPeople:      'ابحث عن موظف…',
    searchChats:       'ابحث عن محادثة أو موظف…',
    people:            'الموظفون',
    noConversations:   'لا توجد محادثات بعد. ابدأ واحدة!',
    noMessagesYet:     'لا توجد رسائل بعد. ابدأ المحادثة!',
    typeMessage:       'اكتب رسالة…',
    send:              'إرسال',
    attachFile:        'إرفاق ملف',
    fileTooLarge:      'حجم الملف كبير جداً (الحد الأقصى 15 ميجابايت).',
    tooManyAttachments:'يمكنك إرفاق حتى 10 ملفات في كل مرة.',
    attachmentPending: 'جاهز للإرسال — لم يُرسل بعد',
    removeAttachment:  'إزالة المرفق',
    sending:           'جارٍ الإرسال…',
    selectConversation:'اختر محادثة لبدء المراسلة.',
    departmentGroup:   'مجموعة القسم',
    deptThread:        'محادثة خاصة مع القسم',
    departmentsSection: 'الأقسام',
    peopleSection:      'الموظفون',
    groupChat:         'محادثة جماعية',
    members:           'الأعضاء',
    onlineNow:         '{n} متصل الآن',
    startChat:         'بدء محادثة',
    you:               'أنت',
    hideChat:          'إخفاء المحادثة',
    unhideChat:        'إلغاء إخفاء المحادثة',
    hiddenChats:       'محادثات مخفية',
    online:            'متصل الآن',
    away:              'بعيد',
    lastSeen:          'آخر ظهور {time}',
    lastSeenNever:     'غير متصل',
    justNow:           'الآن',
    minAgo:            'منذ {n} د',
    hourAgo:           'منذ {n} س',
    dayAgo:            'منذ {n} يوم',
    seen:              'تمت المشاهدة',
    seenBy:            'شاهدها {names}',
    seenByAll:         'شاهدها الجميع',
    typingOne:         '{name} يكتب الآن…',
    typingMultiple:    'عدة أشخاص يكتبون الآن…',
    searchInChat:      'بحث في المحادثة',
    noMatches:         'لا توجد نتائج مطابقة',
    matchOf:           '{i} من {n}',
    enableNotifPrompt: 'فعّل الإشعارات لتنبيهك عند وصول رسائل جديدة.',
    enableNotif:       'تفعيل',
    searchFilters:     'فلاتر البحث',
    anySender:         'أي مرسل',
    fromDate:          'من تاريخ',
    toDate:            'إلى تاريخ',
    clearFilters:      'إزالة الفلاتر',
    loadMoreResults:   'عرض نتائج أخرى',
    notifSettings:     'إعدادات الإشعارات',
    notifDeniedHint:   'الإشعارات محظورة في إعدادات المتصفح. يرجى تفعيلها لهذا الموقع لاستخدام التنبيهات على سطح المكتب.',
    notifLevelMentionsDms:     'الإشارات والرسائل المباشرة',
    notifLevelMentionsDmsHint: 'الموصى به — تنبيه فقط للرسائل المباشرة والمحادثات الجماعية والإشارات. لا تنبيه لدردشة قنوات الأقسام العادية.',
    notifLevelAll:             'كل الرسائل',
    notifLevelAllHint:         'تنبيه لكل رسالة جديدة في كل محادثة، بما في ذلك قنوات الأقسام.',
    notifLevelOff:             'إيقاف',
    notifLevelOffHint:         'بدون إشعارات سطح المكتب. ستظل تظهر لك شارات الرسائل غير المقروءة داخل التطبيق.',
    messagesResults:   'الرسائل',
    addReaction:       'إضافة تعبير',
    moreReactions:     'المزيد من التعابير',
    emojiGroups: { common: 'الشائعة', faces: 'الوجوه', work: 'العمل', signals: 'إشارات' },
    mentionedYou:      'أشار إليك',
    reply:             'رد',
    cancelReply:       'إلغاء الرد',
    attachment:        'مرفق',
    pin:               'تثبيت في الأعلى',
    unpin:             'إلغاء التثبيت',
    pinnedBy:          'مثبَّت من {name}',
    setStatus:         'تعيين الحالة',
    statusPlaceholder: 'ما الذي تفعله؟',
    clearStatus:       'إزالة الحالة',
    statusPresets: ['في اجتماع', 'في إجازة', 'خارج المكتب', 'سأعود حالاً'],
    profilePicture: 'الصورة الشخصية',
    uploadPicture:  'رفع صورة',
    removePicture:  'إزالة',
    avatarColor:    'لون الأيقونة',

    // ── نظام المراسلات الداخلية ──
    deptGroupOffices: 'المكاتب',
    deptGroupDepts:   'الأقسام',
    deptSearchPlaceholder: 'ابحث عن قسم…',
    noDept: 'بدون قسم',
    fromDeptsLabel: 'ما الأقسام التي يمكنها طلب هذه الخدمة؟',
    toDeptsLabel:   'ما الأقسام التي تستلم هذا؟',
    fromDeptsAll:   'كل الأقسام',
    fromDeptsSome:  'مقصورة على {n} قسم',
    dirRequest:     'وارد',
    dirIssue:       'صادر',
    dirLabel:       'الاتجاه',
    dirRequestHint: 'شيء يستلمه هذا القسم',
    dirIssueHint:   'شيء يرسله هذا القسم',
    corr: {
      title: 'المراسلات الداخلية',
      nav: { correspondence: 'المراسلات', dashboard: 'لوحة المراسلات', new: 'مراسلة جديدة',
             inbox: 'صندوق الوارد', approvals: 'الموافقات', returned: 'المُعادة إليّ', archive: 'الأرشيف' },
      statuses:   { pending: 'بانتظار الموافقة', approved: 'موافق عليها', done: 'تم الإنجاز', returned: 'مُعادة للمراجعة' },
      priorities: { high: 'عالية', med: 'متوسطة', low: 'منخفضة' },
      events: { created: 'تم إنشاء المراسلة', approved: 'موافقة رئيس القسم', rejected: 'رفض وإعادة للمراجعة',
                resubmitted: 'تم التعديل وإعادة الإرسال', reply: 'رد', completed: 'تم الإنجاز' },
      reply: {
        label: 'اكتب رداً', placeholder: 'اكتب ردك هنا…',
        send: 'إرسال الرد', sent: 'تم إرسال الرد.',
        needText: 'اكتب رداً أو أرفق ملفاً.',
        withYou: 'بانتظار قسمك', withThem: 'بانتظار {dept}',
        closedHint: 'الإنجاز من صلاحية مُرسل المراسلة أو رئيس قسمه.',
      },
      tiles: { total: 'إجمالي المراسلات', pending: 'بانتظار الموافقة', done: 'تم الإنجاز',
               approved: 'جارية التنفيذ', returned: 'مُعادة للمراجعة' },
      boxHints: { inbox: 'المراسلات الموجهة إلى قسمك', approvals: 'مراسلات قسمك بانتظار موافقتك',
                  returned: 'مراسلات أُعيدت إليك مع بيان السبب', archive: 'كل ما تستطيع الاطلاع عليه' },
      emptyBox: { inbox: 'لا توجد مراسلات في صندوق الوارد.', approvals: 'لا توجد مراسلات بانتظار موافقتك.',
                  returned: 'لا توجد مراسلات مُعادة إليك.', archive: 'لا توجد مراسلات بعد.' },
      willBeSentTo: 'ستُرسل إلى {name} للموافقة',
      approverOnline: 'متصل الآن', approverAway: 'آخر ظهور {when}', approverNoAccount: 'لا يملك حساباً بعد',
      headRole: 'رئيس القسم', deputyRole: 'النائب',
      noApproverYet: 'لم يُحدَّد رئيس لقسمك بعد — ستتم الموافقة من مدير النظام.',
      addFiles: 'إضافة ملفات', charCount: '{n} حرف',
      toastApproved: 'تمت الموافقة على المراسلة',
      toastRejected: 'تمت إعادة المراسلة إلى الموظف مع بيان السبب',
      toastCompleted: 'تم تسجيل الإنجاز',
      newTitle: 'مراسلة جديدة', newSubtitle: 'تُرسل إلى رئيس قسمك للموافقة قبل وصولها إلى القسم المستلم.',
      editReturnedTitle: 'تعديل المراسلة المُعادة',
      editingNotice: 'أنت تُعدّل مراسلة مُعادة',
      recentTitle: 'أحدث المراسلات',
      serial: 'رقم المراسلة', subject: 'الموضوع', sender: 'المرسِل', fromDept: 'القسم المرسِل',
      toDept: 'القسم المستلم', date: 'التاريخ', priority: 'الأولوية', status: 'الحالة',
      body: 'نص المراسلة', attachments: 'المرفقات', timeline: 'سجل الموافقات',
      requestType: 'الموضوع', other: 'أخرى (كتابة الموضوع يدوياً)',
      svcWeIssue: 'ما نرسله إليهم', svcTheyAccept: 'ما نطلبه منهم',
      subjectPlaceholder: 'اكتب موضوع المراسلة', bodyPlaceholder: 'اكتب نص المراسلة',
      choose: 'اختر…', pickDeptFirst: 'اختر القسم المستلم أولاً',
      all: 'الكل', searchPlaceholder: 'ابحث في الموضوع أو رقم المراسلة…',
      send: 'إرسال', resubmit: 'حفظ وإعادة الإرسال', approve: 'موافقة', reject: 'رفض وإعادة',
      complete: 'تم الإنجاز', viewDetails: 'عرض التفاصيل', editResend: 'تعديل وإعادة الإرسال',
      reviewIt: 'مراجعة', removeFile: 'إزالة الملف',
      rejectModalTitle: 'سبب الرفض وإعادة الطلب', rejectReason: 'سبب الإعادة',
      rejectReasonPlaceholder: 'وضّح المطلوب تعديله', rejectConfirm: 'إعادة الطلب للموظف',
      dropHint: 'اسحب الملفات هنا، أو اضغط للاختيار', dropLimit: 'بحد أقصى 10MB لكل ملف',
      existingAttachments: 'يوجد {n} مرفق على هذه المراسلة',
      sentToHead: 'تم إرسال المراسلة إلى رئيس القسم للموافقة',
      resubmitted: 'تمت إعادة إرسال المراسلة إلى رئيس القسم',
      tooBig: 'الملف "{name}" أكبر من 10MB', dupFile: 'الملف "{name}" مضاف مسبقاً',
      errToDept: 'يرجى اختيار القسم المستلم.', errType: 'يرجى اختيار نوع الطلب.',
      errSubject: 'الموضوع مطلوب.', errBody: 'نص المراسلة مطلوب.',
      errReason: 'سبب الرفض مطلوب.',
      noDeptTitle: 'لا يوجد قسم مُسند لحسابك',
      noDeptBody: 'لم يتم إسناد قسم لحسابك، لذلك لا يمكن إرسال مراسلات باسمك. يرجى مراجعة مدير النظام.',
      print: { button: 'طباعة', kingdom: 'مملكة البحرين',
               administration: 'الإدارة العامة للشؤون السنية',
               systemName: 'نظام المراسلات الداخلية', refNo: 'رقم المراسلة',
               bismillah: 'بِسْمِ اللهِ الرَّحْمَنِ الرَّحِيمِ',
               officialMemo: 'مراسلة رسمية داخلية', messrs: 'السادة',
               mayGodProtect: 'حفظكم الله،،،', greeting: 'السلام عليكم ورحمة الله وبركاته،',
               closing: 'وتفضلوا بقبول فائق الاحترام والتقدير،،،', printedOn: 'تاريخ الطباعة' },
    },
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LANG_KEY) || 'ar');

  useEffect(() => {
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir  = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const toggle = () => setLang(l => (l === 'ar' ? 'en' : 'ar'));
  const isRTL  = lang === 'ar';
  const t      = T[lang];

  // Department names come back from the API in Arabic only — they live in
  // departments.json, which has one label per department. groupLabels carries
  // both languages, so this is what turns "الموارد البشرية" into "Human
  // Resources" when EN is selected. Falls back to whatever the server sent, so
  // a department added through the admin panel still shows a name.
  const deptName = useCallback(
    (id, fallback) => (id && t.groupLabels?.[id]) || fallback || id || '',
    [t]
  );

  return (
    <LangContext.Provider value={{ lang, t, toggle, isRTL, deptName }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be inside <LangProvider>');
  return ctx;
}
