import React, { createContext, useContext, useState, useEffect } from 'react';

const LANG_KEY = 'doctracking_lang';

const T = {
  en: {
    appName:    'Document Tracking System',
    orgName:    'General Administration of Sunni Endowments',
    signIn:     'Sign In',
    signOut:    'Sign Out',
    signingIn:  'Signing in…',
    username:   'Username',
    password:   'Password',
    usernamePH: 'Username or user@domain.com',
    welcome:    'Welcome',
    dept:       'Department',
    adminPanel: 'Admin Panel',
    loading:    'Loading…',
    na:         'N/A',
    departments:'Departments',
    newRecord:  'New Record',
    submit:     'Submit',
    reset:      'Reset',
    required:   'Required',
    save:       'Save',
    cancel:     'Cancel',
    edit:       'Edit',
    del:        'Delete',
    add:        'Add',
    confirmDel: 'Are you sure? This cannot be undone.',
    selectDept: 'Select a department from the sidebar to begin.',
    submitted:  'Submitted successfully.',
    deptFields:       'Departments',
    roleMaps:         'AD Auto-Roles',
    config:           'Backup',
    addDept:          'Add Department',
    deptLabel:        'Department Name',
    adGroup:          'AD Group (optional)',
    adGroupHint:      'The Active Directory group CN linked to this department (used for automatic task routing).',
    fields:           'fields',
    addField:         '+ Add Field',
    fieldKey:         'Field key',
    fieldLabel:       'Display label',
    fieldType:        'Type',
    fieldReq:         'Required',
    optionsPH:        'Option1, Option2, Option3',
    actions:          'Actions',
    optPH:            'Options / Placeholder',
    exportJSON:       'Download Backup',
    previewCfg:       'Preview',
    importCfg:        'Import & Apply',
    importPH:         '{"departments": [...], "roleGroupMap": {...}}',
    importNote:       'Paste a backup JSON to restore (replaces all departments and role mappings):',
    cfgNote:          'Download a backup of all department and role settings, or restore from a previous backup.',
    ldapNote:         'When an AD user logs in without a manually assigned role, their group membership is used to auto-assign a role. Add the group CN and choose a role.',
    adAutoRolesNote:  'These rules run automatically on login. For manual role assignment per person, use the Users page instead.',
    roleMap:          'AD Group → Auto Role',
    newGroup:         'group_cn_name',
    deptNote:         'Departments appear immediately in all dropdowns (users, task creation) after saving.',
    usersInDept:      'users',
    advancedOptions:  'Advanced',
    customFields:     'Custom Fields',
    customFieldsNote: 'Extra fields shown when creating a task for this department.',
    noDepts:          'No departments yet. Add one to get started.',

    // Bulk actions
    selectAll:        'Select all',
    selected:         'selected',
    bulkForward:      'Forward All',
    bulkClose:        'Close All',
    clearSelection:   'Clear',
    bulkDone:         'Done — {n} tasks updated.',
    selectDeptBulk:   'Forward {n} tasks to:',

    // Task templates
    templates:        'Templates',
    templateName:     'Template Name',
    useTemplate:      'Use Template',
    noTemplate:       'No Template',
    addTemplate:      'Add Template',
    editTemplate:     'Edit Template',
    templateSaved:    'Template saved.',
    templateDeleted:  'Template deleted.',
    noTemplates:      'No templates yet.',
    expectedDays:     'Expected Days',
    templatesNote:    'Pre-fill common task fields. Available to all staff when creating tasks.',

    // Sessions
    activeSessions:   'Active Sessions',
    sessionsNote:     'All currently logged-in users. Force logout terminates their session immediately.',
    forceLogout:      'Force Logout',
    sessionTerminated:'Session terminated.',
    noSessions:       'No active sessions.',
    loggedInAt:       'Logged in',
    expiresAt:        'Expires',
    yourSession:      'You',

    // Audit log
    auditLog:         'Audit Log',
    auditActor:       'User',
    auditAction:      'Action',
    auditTarget:      'Target',
    auditTime:        'Time',
    auditFilter:      'Filter by user…',
    noAuditLogs:      'No log entries.',
    auditActions: {
      USER_LOGIN:          'Logged in',
      USER_LOGOUT:         'Logged out',
      TASK_CREATED:        'Task created',
      TASK_FORWARDED:      'Task forwarded',
      TASK_CLOSED:         'Task closed',
      USER_CREATED:        'User created',
      USER_UPDATED:        'User updated',
      USER_DELETED:        'User deleted',
      LDAP_ROLE_ASSIGNED:  'Role assigned',
      SESSION_TERMINATED:  'Session terminated',
    },

    // Dashboard dept filter
    allDepartments:   'All Departments',
    viewingDept:      'Viewing:',
    deptStats:        'Department Stats',

    // Navigation
    dashboard:  'Dashboard',
    tasks:      'Tasks',
    myTasks:    'My Tasks',
    allTasks:   'All Tasks',
    users:      'Users',
    settings:   'Settings',
    deptForms:  'Department Forms',

    // Task workflow
    createTask:     'Create Task',
    taskTitle:      'Task Title',
    taskType:       'Type',
    taskPriority:   'Priority',
    taskStatus:     'Status',
    taskSerial:     'Serial',
    taskCreated:    'Created',
    taskAssigned:   'Assigned To',
    taskSource:     'Source / Sender',
    taskDelivery:   'Delivery Method',
    taskExpected:   'Expected Completion',
    taskCompleted:  'Completed On',
    taskNote:       'Notes',
    forwardTask:    'Forward to Department',
    returnToCS:     'Return to CS',
    closeTask:      'Close Task',
    addComment:     'Add Comment',
    markReceived:   'Received',
    receivedAdded:  'Marked as received.',
    taskHistory:    'Activity History',
    selectDeptFwd:  'Select destination department',
    confirmClose:   'Are you sure you want to close this task?',
    confirmReturn:  'Return this task to Customer Service?',
    taskClosed:     'Task closed successfully.',
    taskForwarded:  'Task forwarded.',
    taskReturned:   'Task returned to CS.',
    commentAdded:   'Comment added.',

    types:     { incoming: 'Incoming', outgoing: 'Outgoing' },
    priorities:{ low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent' },
    statuses:  { new: 'New', assigned: 'Assigned', in_progress: 'In Progress', returned: 'Returned', closed: 'Closed' },
    eventTypes:{
      created:   'Task created',
      forwarded: 'Forwarded to',
      returned:  'Returned to CS',
      commented: 'Comment',
      closed:    'Closed',
    },

    // Users
    fullName:     'Full Name',
    email:        'Email',
    role:         'Role',
    deptAssign:   'Department',
    active:       'Active',
    inactive:     'Inactive',
    addUser:      '+ Add User',
    editUser:     'Edit User',
    newPassword:  'New Password (leave blank to keep current)',
    userCreated:  'User created.',
    userUpdated:  'User updated.',
    userDeleted:  'User deleted.',
    ldapUsers:          'Network Users (Active Directory)',
    ldapNotConfigured:  'LDAP service account not configured. Set LDAP_BIND_DN and LDAP_BIND_PASSWORD in the server .env file.',
    ldapTitle:          'Job Title',
    localUsers:         'Local Users',
    localUsersNote:     'Manually added accounts with password login',
    noLdapUsers:        'No users found in Active Directory.',
    noResults:          'No results found.',
    refresh:            'Refresh',
    assignRole:         'Assign Role',
    editRole:           'Edit Role',
    unassigned:         'No role assigned',
    ldapAssignTitle:    'Assign Role — Network User',
    roleAssigned:       'Role assigned.',
    rolesGuide:         'Roles Reference',
    rolesGuideNote:     'Assigned across all accounts (AD + local)',
    assigned:           'assigned',
    roleDesc: {
      SUPER_ADMIN:      'Full system access — manage users, settings, and all tasks across every department.',
      ADMIN:            'View and manage all tasks across all departments. Cannot manage users or system settings.',
      CUSTOMER_SERVICE: 'Create tasks and route them to departments. Sees all tasks across all departments. No department assignment needed.',
      MANAGER:          'Create tasks for Customer Service using their department\'s forms. Can return tasks assigned to their department. Requires a department assignment.',
      STAFF:            'Create tasks for Customer Service using their department\'s forms. View and act on tasks assigned to their department. Requires a department assignment.',
      READONLY:         'View tasks in their department only. No create or action permissions. Requires a department assignment.',
    },
    deptHint:        'Determines which form the user sees when creating a task.',
    deptNotRequired: 'Not required for this role — this role has access to all departments.',

    // Dashboard
    totalTasks:    'Total Tasks',
    openTasks:     'Open',
    closedTasks:   'Closed',
    returnedTasks: 'Returned',
    totalUsers:    'Total Users',
    byDept:        'Tasks by Department',
    recentTasks:   'Recent Tasks',
    noTasks:       'No tasks yet.',
    noUsers:       'No users yet.',

    overdue:           'Overdue',
    overdueTasks:      'Overdue Tasks',
    notifications:     'Notifications',
    markAllRead:       'Mark all read',
    noNotifications:   'No notifications yet.',
    search:            'Search…',
    roles: {
      SUPER_ADMIN:      'Super Admin',
      ADMIN:            'Admin',
      CUSTOMER_SERVICE: 'Customer Service',
      MANAGER:          'Manager',
      STAFF:            'Staff',
      READONLY:         'Read Only',
    },
    groupLabels: {
      board_office:                'Board Chairman Office',
      director_general_office:     'Director General Office',
      strategic_planning_dept:     'Strategic Planning & Projects',
      investments_dept:            'Endowment Investments',
      revenue_collection_dept:     'Revenue Collection',
      endowment_disbursement_dept: 'Endowment Disbursement & Development',
      sharia_studies_dept:         'Sharia Endowment & Studies',
      legal_affairs_dept:          'Legal Affairs & Endowment Properties',
      engineering_services_dept:   'Projects & Engineering Services',
      accounts_dept:               'Accounts',
      hr_dept:                     'Human Resources',
      procurement_dept:            'Procurement',
      it_dept:                     'Information Technology',
      admin_affairs_dept:          'Administrative Affairs',
      mosques_guidance_dept:       'Mosques & Religious Guidance',
      community_relations_dept:    'Communication & Community Service',
      maintenance_dept:            'Maintenance',
      reception_dept:              'Reception',
      other_dept:                  'Other',
    },

    // Messages / Chat
    messages:          'Messages',
    newChat:           'New Conversation',
    searchPeople:      'Search people…',
    searchChats:       'Search chats and people…',
    people:            'People',
    noConversations:   'No conversations yet. Start one!',
    noMessagesYet:     'No messages yet. Say hello!',
    typeMessage:       'Type a message…',
    send:              'Send',
    attachFile:        'Attach a file',
    fileTooLarge:      'File is too large (max 15MB).',
    selectConversation:'Select a conversation to start messaging.',
    departmentGroup:   'Department group',
    online:            'Online',
    away:              'Away',
    lastSeen:          'Last seen {time}',
    lastSeenNever:     'Offline',
    justNow:           'Just now',
    minAgo:            '{n}m ago',
    hourAgo:           '{n}h ago',
    dayAgo:            '{n}d ago',
  },

  ar: {
    appName:    'نظام تتبع الوثائق',
    orgName:    'الإدارة العامة للأوقاف السنية',
    signIn:     'تسجيل الدخول',
    signOut:    'خروج',
    signingIn:  'جاري الدخول…',
    username:   'اسم المستخدم',
    password:   'كلمة المرور',
    usernamePH: 'اسم المستخدم أو البريد الإلكتروني',
    welcome:    'مرحباً',
    dept:       'القسم',
    adminPanel: 'الإعدادات',
    loading:    'جاري التحميل…',
    na:         'غير محدد',
    departments:'الأقسام',
    newRecord:  'سجل جديد',
    submit:     'إرسال',
    reset:      'إعادة تعيين',
    required:   'مطلوب',
    save:       'حفظ',
    cancel:     'إلغاء',
    edit:       'تعديل',
    del:        'حذف',
    add:        'إضافة',
    confirmDel: 'هل أنت متأكد؟ لا يمكن التراجع.',
    selectDept: 'اختر قسماً من القائمة الجانبية للبدء.',
    submitted:  'تم الإرسال بنجاح.',
    deptFields:       'الأقسام',
    roleMaps:         'الأدوار التلقائية (AD)',
    config:           'النسخ الاحتياطي',
    addDept:          'إضافة قسم',
    deptLabel:        'اسم القسم',
    adGroup:          'مجموعة AD (اختياري)',
    adGroupHint:      'اسم CN لمجموعة Active Directory المرتبطة بهذا القسم (يُستخدم لتوجيه المهام تلقائياً).',
    fields:           'حقل',
    addField:         '+ إضافة حقل',
    fieldKey:         'مفتاح الحقل',
    fieldLabel:       'التسمية',
    fieldType:        'النوع',
    fieldReq:         'مطلوب',
    optionsPH:        'خيار1، خيار2، خيار3',
    actions:          'الإجراءات',
    optPH:            'الخيارات / النص التوضيحي',
    exportJSON:       'تنزيل نسخة احتياطية',
    previewCfg:       'معاينة',
    importCfg:        'استيراد وتطبيق',
    importPH:         '{"departments": [...], "roleGroupMap": {...}}',
    importNote:       'الصق JSON للاستعادة (يستبدل جميع الأقسام وتعيينات الأدوار):',
    cfgNote:          'قم بتنزيل نسخة احتياطية من إعدادات الأقسام والأدوار، أو الاستعادة من نسخة سابقة.',
    ldapNote:         'عند تسجيل دخول مستخدم AD دون دور محدد يدوياً، يُعيَّن الدور تلقائياً بناءً على عضوية المجموعة. أضف اسم CN واختر الدور.',
    adAutoRolesNote:  'تُطبَّق هذه القواعد تلقائياً عند تسجيل الدخول. لتعيين الأدوار يدوياً لكل شخص، استخدم صفحة المستخدمين.',
    roleMap:          'مجموعة AD ← الدور التلقائي',
    newGroup:         'اسم_المجموعة_cn',
    deptNote:         'تظهر الأقسام فوراً في جميع القوائم المنسدلة (المستخدمون، إنشاء المهام) بعد الحفظ.',
    usersInDept:      'مستخدم',
    advancedOptions:  'خيارات متقدمة',
    customFields:     'الحقول المخصصة',
    customFieldsNote: 'حقول إضافية تظهر عند إنشاء مهمة لهذا القسم.',
    noDepts:          'لا توجد أقسام بعد. أضف قسماً للبدء.',

    // Bulk actions
    selectAll:        'تحديد الكل',
    selected:         'محدد',
    bulkForward:      'إحالة الكل',
    bulkClose:        'إغلاق الكل',
    clearSelection:   'إلغاء',
    bulkDone:         'تم — {n} مهام محدّثة.',
    selectDeptBulk:   'إحالة {n} مهام إلى:',

    // Task templates
    templates:        'القوالب',
    templateName:     'اسم القالب',
    useTemplate:      'استخدام قالب',
    noTemplate:       'بدون قالب',
    addTemplate:      'إضافة قالب',
    editTemplate:     'تعديل القالب',
    templateSaved:    'تم حفظ القالب.',
    templateDeleted:  'تم حذف القالب.',
    noTemplates:      'لا توجد قوالب بعد.',
    expectedDays:     'الأيام المتوقعة',
    templatesNote:    'قوالب لملء حقول المهام مسبقاً. متاحة لجميع الموظفين عند إنشاء مهمة.',

    // Sessions
    activeSessions:   'الجلسات النشطة',
    sessionsNote:     'جميع المستخدمين الذين سجلوا الدخول حالياً. إنهاء الجلسة يُبطل صلاحيتهم فوراً.',
    forceLogout:      'إنهاء الجلسة',
    sessionTerminated:'تم إنهاء الجلسة.',
    noSessions:       'لا توجد جلسات نشطة.',
    loggedInAt:       'دخل في',
    expiresAt:        'تنتهي في',
    yourSession:      'أنت',

    // Audit log
    auditLog:         'سجل المراقبة',
    auditActor:       'المستخدم',
    auditAction:      'الإجراء',
    auditTarget:      'الهدف',
    auditTime:        'الوقت',
    auditFilter:      'تصفية بالمستخدم…',
    noAuditLogs:      'لا توجد سجلات.',
    auditActions: {
      USER_LOGIN:          'تسجيل دخول',
      USER_LOGOUT:         'تسجيل خروج',
      TASK_CREATED:        'إنشاء مهمة',
      TASK_FORWARDED:      'إحالة مهمة',
      TASK_CLOSED:         'إغلاق مهمة',
      USER_CREATED:        'إنشاء مستخدم',
      USER_UPDATED:        'تحديث مستخدم',
      USER_DELETED:        'حذف مستخدم',
      LDAP_ROLE_ASSIGNED:  'تعيين دور',
      SESSION_TERMINATED:  'إنهاء جلسة',
    },

    // Dashboard dept filter
    allDepartments:   'جميع الأقسام',
    viewingDept:      'عرض:',
    deptStats:        'إحصائيات القسم',

    // Navigation
    dashboard:  'لوحة المتابعة',
    tasks:      'المهام',
    myTasks:    'مهامي',
    allTasks:   'جميع المهام',
    users:      'المستخدمون',
    settings:   'إعدادات النظام',
    deptForms:  'نماذج الأقسام',

    // Task workflow
    createTask:     'إنشاء مهمة',
    taskTitle:      'عنوان المهمة',
    taskType:       'النوع',
    taskPriority:   'الأولوية',
    taskStatus:     'الحالة',
    taskSerial:     'الرقم التسلسلي',
    taskCreated:    'تاريخ الإنشاء',
    taskAssigned:   'محال إلى',
    taskSource:     'الجهة المرسلة',
    taskDelivery:   'طريقة الاستلام',
    taskExpected:   'تاريخ الإنجاز المتوقع',
    taskCompleted:  'تاريخ الإنجاز الفعلي',
    taskNote:       'ملاحظات',
    forwardTask:    'إحالة إلى قسم',
    returnToCS:     'إرجاع لخدمة العملاء',
    closeTask:      'إغلاق المهمة',
    addComment:     'إضافة تعليق',
    markReceived:   'تم الاستلام',
    receivedAdded:  'تم تسجيل الاستلام.',
    taskHistory:    'سجل النشاط',
    selectDeptFwd:  'اختر القسم المحال إليه',
    confirmClose:   'هل تريد إغلاق هذه المهمة؟',
    confirmReturn:  'هل تريد إرجاع المهمة إلى خدمة العملاء؟',
    taskClosed:     'تم إغلاق المهمة.',
    taskForwarded:  'تم إحالة المهمة.',
    taskReturned:   'تم إرجاع المهمة لخدمة العملاء.',
    commentAdded:   'تمت إضافة التعليق.',

    types:     { incoming: 'وارد', outgoing: 'صادر' },
    priorities:{ low: 'منخفضة', normal: 'عادية', high: 'عالية', urgent: 'عاجلة' },
    statuses:  { new: 'جديدة', assigned: 'محالة', in_progress: 'قيد التنفيذ', returned: 'مُرجَعة', closed: 'مغلقة' },
    eventTypes:{
      created:   'تم إنشاء المهمة',
      forwarded: 'أُحيلت إلى',
      returned:  'أُرجعت لخدمة العملاء',
      commented: 'تعليق',
      closed:    'تم الإغلاق',
    },

    // Users
    fullName:     'الاسم الكامل',
    email:        'البريد الإلكتروني',
    role:         'الدور',
    deptAssign:   'القسم',
    active:       'نشط',
    inactive:     'غير نشط',
    addUser:      '+ إضافة مستخدم',
    editUser:     'تعديل المستخدم',
    newPassword:  'كلمة مرور جديدة (اتركها فارغة للإبقاء على الحالية)',
    userCreated:  'تم إنشاء المستخدم.',
    userUpdated:  'تم تحديث المستخدم.',
    userDeleted:  'تم حذف المستخدم.',
    ldapUsers:          'مستخدمو الشبكة (Active Directory)',
    ldapNotConfigured:  'لم يتم تكوين حساب خدمة LDAP. أضف LDAP_BIND_DN و LDAP_BIND_PASSWORD في ملف .env الخاص بالخادم.',
    ldapTitle:          'المسمى الوظيفي',
    localUsers:         'المستخدمون المحليون',
    localUsersNote:     'حسابات مضافة يدوياً بكلمة مرور',
    noLdapUsers:        'لم يتم العثور على مستخدمين في Active Directory.',
    noResults:          'لا توجد نتائج.',
    refresh:            'تحديث',
    assignRole:         'تعيين دور',
    editRole:           'تعديل الدور',
    unassigned:         'لم يُعيَّن دور',
    ldapAssignTitle:    'تعيين دور — مستخدم الشبكة',
    roleAssigned:       'تم تعيين الدور.',
    rolesGuide:         'دليل الأدوار',
    rolesGuideNote:     'الأدوار المُعيَّنة في جميع الحسابات (الشبكة + المحلية)',
    assigned:           'مُعيَّن',
    roleDesc: {
      SUPER_ADMIN:      'صلاحية كاملة — إدارة المستخدمين والإعدادات وجميع المهام في جميع الأقسام.',
      ADMIN:            'عرض وإدارة جميع المهام في جميع الأقسام. لا يمكنه إدارة المستخدمين أو الإعدادات.',
      CUSTOMER_SERVICE: 'إنشاء المهام وتحويلها للأقسام. يرى جميع المهام في جميع الأقسام. لا يحتاج إلى تعيين قسم.',
      MANAGER:          'ينشئ مهاماً لخدمة العملاء عبر نموذج قسمه. يُعيد المهام المُحالة لقسمه. يشترط تعيين القسم.',
      STAFF:            'ينشئ مهاماً لخدمة العملاء عبر نموذج قسمه. يعمل على المهام المُحالة لقسمه. يشترط تعيين القسم.',
      READONLY:         'عرض المهام في قسمه فقط. لا صلاحية للإنشاء أو اتخاذ أي إجراء. يشترط تعيين القسم.',
    },
    deptHint:        'يحدد النموذج الذي يراه المستخدم عند إنشاء مهمة جديدة.',
    deptNotRequired: 'لا يلزم لهذا الدور — يملك صلاحية الوصول لجميع الأقسام.',

    // Dashboard
    totalTasks:    'إجمالي المهام',
    openTasks:     'مفتوحة',
    closedTasks:   'مغلقة',
    returnedTasks: 'مُرجَعة',
    totalUsers:    'المستخدمون',
    byDept:        'المهام حسب القسم',
    recentTasks:   'أحدث المهام',
    noTasks:       'لا توجد مهام بعد.',
    noUsers:       'لا يوجد مستخدمون بعد.',

    overdue:           'متأخرة',
    overdueTasks:      'المهام المتأخرة',
    notifications:     'الإشعارات',
    markAllRead:       'تعليم الكل كمقروء',
    noNotifications:   'لا توجد إشعارات بعد.',
    search:            'بحث…',
    roles: {
      SUPER_ADMIN:      'مدير النظام',
      ADMIN:            'مشرف',
      CUSTOMER_SERVICE: 'خدمة العملاء',
      MANAGER:          'مدير',
      STAFF:            'موظف',
      READONLY:         'قراءة فقط',
    },
    groupLabels: {
      board_office:                'مكتب رئيس المجلس',
      director_general_office:     'مكتب المدير العام',
      strategic_planning_dept:     'التخطيط الاستراتيجي ومتابعة المشاريع الوقفية',
      investments_dept:            'الاستثمارات الوقفية',
      revenue_collection_dept:     'تحصيل الإيرادات',
      endowment_disbursement_dept: 'المصارف الوقفية وتنمية الوقف',
      sharia_studies_dept:         'الوقف الشرعي والدراسات',
      legal_affairs_dept:          'الشؤون القانونية والأملاك الوقفية',
      engineering_services_dept:   'المشاريع والخدمات الهندسية',
      accounts_dept:               'الحسابات',
      hr_dept:                     'الموارد البشرية',
      procurement_dept:            'المشتريات',
      it_dept:                     'تقنية المعلومات',
      admin_affairs_dept:          'الشؤون الإدارية',
      mosques_guidance_dept:       'المساجد والإرشاد الديني',
      community_relations_dept:    'الإتصال وخدمة المجتمع',
      maintenance_dept:            'الصيانة',
      reception_dept:              'الإستقبال',
      other_dept:                  'أخرى',
    },

    // Messages / Chat
    messages:          'المراسلات',
    newChat:           'محادثة جديدة',
    searchPeople:      'ابحث عن موظف…',
    searchChats:       'ابحث عن محادثة أو موظف…',
    people:            'الموظفون',
    noConversations:   'لا توجد محادثات بعد. ابدأ واحدة!',
    noMessagesYet:     'لا توجد رسائل بعد. ابدأ المحادثة!',
    typeMessage:       'اكتب رسالة…',
    send:              'إرسال',
    attachFile:        'إرفاق ملف',
    fileTooLarge:      'حجم الملف كبير جداً (الحد الأقصى 15 ميجابايت).',
    selectConversation:'اختر محادثة لبدء المراسلة.',
    departmentGroup:   'مجموعة القسم',
    online:            'متصل الآن',
    away:              'بعيد',
    lastSeen:          'آخر ظهور {time}',
    lastSeenNever:     'غير متصل',
    justNow:           'الآن',
    minAgo:            'منذ {n} د',
    hourAgo:           'منذ {n} س',
    dayAgo:            'منذ {n} يوم',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LANG_KEY) || 'ar');

  useEffect(() => {
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir  = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const toggle = () => setLang(l => (l === 'ar' ? 'en' : 'ar'));
  const isRTL  = lang === 'ar';
  const t      = T[lang];

  return (
    <LangContext.Provider value={{ lang, t, toggle, isRTL }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be inside <LangProvider>');
  return ctx;
}
